#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash
# vim: set ft=bash ts=4 sw=4 sts=4 et :

declare -r log_prefix="[init-db-wait]"

declare -ri TIMEOUT=60
declare -i ATTEMPT=0
declare -i DELAY=0
declare -i STARTED_AT=${EPOCHSECONDS:?EPOCHSECONDS var unset}

delay_next_attempt() {
    local -i elapsed=$(( EPOCHSECONDS - STARTED_AT ))
    local -ri remaining=$(( TIMEOUT - elapsed ))

    if (( remaining <= 0 )); then
        echo "${log_prefix} Unable to connect after $elapsed seconds."
        exit 1
    fi

    DELAY+=1

    # clamp to remaining time
    if (( DELAY > remaining )); then
        DELAY=$remaining
    fi

    ATTEMPT+=1
    echo "${log_prefix} Attempt $ATTEMPT failed! Trying again in $DELAY seconds..."
    sleep "$DELAY"
}

wait_for_postgres() {
	echo "${log_prefix} Waiting for PostgreSQL to start..."

	local -r host="${PAPERLESS_DBHOST:-localhost}"
	local -r port="${PAPERLESS_DBPORT:-5432}"
	local -r user="${PAPERLESS_DBUSER:-paperless}"

	# Disable warning, host and port can't have spaces
	# shellcheck disable=SC2086
	while [ ! "$(pg_isready -h ${host} -p ${port} --username ${user})" ]; do
        delay_next_attempt
	done
	echo "Connected to PostgreSQL"
}

wait_for_mariadb() {
	echo "${log_prefix} Waiting for MariaDB to start..."

	local -r host="${PAPERLESS_DBHOST:=localhost}"
	local -r port="${PAPERLESS_DBPORT:=3306}"

	# Disable warning, host and port can't have spaces
	# shellcheck disable=SC2086
	while ! true > /dev/tcp/$host/$port; do
        delay_next_attempt
	done
	echo "Connected to MariaDB"
}

if [[ "${PAPERLESS_DBENGINE}" == "mariadb" ]]; then
	echo "${log_prefix} Waiting for MariaDB to report ready"
	wait_for_mariadb
elif [[ -n "${PAPERLESS_DBHOST}" ]]; then
	echo "${log_prefix} Waiting for postgresql to report ready"
	wait_for_postgres
fi

	echo "${log_prefix} Database is ready"
