# Generated by Django 3.1.3 on 2020-11-17 13:34

from django.db import migrations
from django.db.migrations import RunPython


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0001_initial"),
    ]

    operations = [RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
