# Generated by Django 5.1.6 on 2025-02-24 16:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0002_optimize_integer_field_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="stop_processing",
            field=models.BooleanField(
                default=False,
                help_text="If True, no further rules will be processed after this one if any document is consumed.",
                verbose_name="Stop processing further rules",
            ),
        ),
    ]
