# Generated by Django 3.1.3 on 2020-11-18 19:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0002_auto_20201117_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaccount",
            name="imap_port",
            field=models.IntegerField(
                blank=True,
                help_text="This is usually 143 for unencrypted and STARTTLS connections, and 993 for SSL connections.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailrule",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
