# Generated by Django 5.2.16 on 2026-07-18 19:20

import django.db.models.deletion
from django.db import migrations
from django.db import models

CUSTOM_FIELD_MODEL = "documents.customfield"


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_widen_workflow_integer_fields"),
        ("paperless_mail", "0004_processedmail_uid_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="assign_created_from",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Document (extracted date or import time)"),
                    (2, "Email's Date header"),
                ],
                default=1,
                verbose_name="Created date source",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="assign_message_date_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"data_type": "date"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=CUSTOM_FIELD_MODEL,
                verbose_name="assign email message date to custom field",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="assign_recipient_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"data_type": "string"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=CUSTOM_FIELD_MODEL,
                verbose_name="assign email recipient to custom field",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="assign_sender_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"data_type": "string"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=CUSTOM_FIELD_MODEL,
                verbose_name="assign email sender to custom field",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="assign_subject_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"data_type": "string"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=CUSTOM_FIELD_MODEL,
                verbose_name="assign email subject to custom field",
            ),
        ),
    ]
