# Generated by Django 3.2.12 on 2022-03-11 15:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0008_auto_20210516_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="assign_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="mail_rules_multi",
                to="documents.Tag",
                verbose_name="assign this tag",
            ),
        ),
    ]
