# Generated by Django 4.0.3 on 2022-03-28 17:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0008_auto_20210516_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailrule",
            name="action",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Mark as read, don't process read mails"),
                    (2, "Flag the mail, don't process flagged mails"),
                    (3, "Move to specified folder"),
                    (4, "Delete"),
                ],
                default=3,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="mailrule",
            name="folder",
            field=models.CharField(
                default="INBOX",
                help_text="Subfolders must be separated by a delimiter, often a dot ('.') or slash ('/'), but it varies by mail server.",
                max_length=256,
                verbose_name="folder",
            ),
        ),
    ]
