# Generated by Django 4.0.4 on 2022-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0010_mailrule_consumption_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailrule",
            name="action",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Delete"),
                    (2, "Move to specified folder"),
                    (3, "Mark as read, don't process read mails"),
                    (4, "Flag the mail, don't process flagged mails"),
                ],
                default=3,
                verbose_name="action",
            ),
        ),
    ]
