# Generated by Django 3.2.12 on 2022-03-11 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0010_auto_20220311_1602"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailrule",
            name="assign_tag",
        ),
    ]
