# Generated by Django 4.0.4 on 2022-05-29 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0014_alter_mailrule_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailrule",
            name="action",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Delete"),
                    (2, "Move to specified folder"),
                    (3, "Mark as read, don't process read mails"),
                    (4, "Flag the mail, don't process flagged mails"),
                    (5, "Tag the mail with specified tag, don't process tagged mails"),
                ],
                default=3,
                verbose_name="action",
            ),
        ),
    ]
