# Generated by Django 4.0.4 on 2022-04-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0011_alter_mailrule_action"),
        ("paperless_mail", "0014_alter_mailrule_action"),
    ]

    operations = []
