# Generated by Django 4.0.4 on 2022-07-11 22:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0015_alter_mailrule_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="consumption_scope",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Only process attachments."),
                    (
                        2,
                        "Process full Mail (with embedded attachments in file) as .eml",
                    ),
                    (
                        3,
                        "Process full Mail (with embedded attachments in file) as .eml + process attachments as separate documents",
                    ),
                ],
                default=1,
                verbose_name="consumption scope",
            ),
        ),
    ]
