# Generated by Django 4.1.5 on 2023-02-21 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paperless_mail", "0017_mailaccount_owner_mailrule_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedMail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(max_length=256, verbose_name="folder")),
                ("uid", models.CharField(max_length=256, verbose_name="folder")),
                ("status", models.CharField(max_length=256, verbose_name="status")),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="error"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paperless_mail.mailrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
