# Generated by Django 4.1.7 on 2023-03-22 17:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0019_mailrule_filter_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailaccount",
            name="is_token",
            field=models.BooleanField(
                default=False,
                verbose_name="Is token authentication",
            ),
        ),
    ]
