# Generated by Django 4.1.7 on 2023-04-20 15:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0020_mailaccount_is_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaccount",
            name="password",
            field=models.CharField(max_length=2048, verbose_name="password"),
        ),
    ]
