# Generated by Django 4.1.11 on 2023-09-18 18:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0021_alter_mailaccount_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="assign_owner_from_rule",
            field=models.BooleanField(
                default=True,
                verbose_name="Assign the rule owner to documents",
            ),
        ),
        migrations.AlterField(
            model_name="mailrule",
            name="assign_title_from",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Use subject as title"),
                    (2, "Use attachment filename as title"),
                    (3, "Do not assign title from rule"),
                ],
                default=1,
                verbose_name="assign title from",
            ),
        ),
    ]
