# Generated by Django 4.2.11 on 2024-04-22 20:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0023_remove_mailrule_filter_attachment_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailaccount",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processedmail",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processedmail",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
