# Generated by Django 5.1.1 on 2024-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless_mail', '0025_alter_mailaccount_owner_alter_mailrule_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether fetching of mail for this account is enabled.', verbose_name='enabled'),
        ),
    ]
