# Generated by Django 5.1.1 on 2024-10-05 17:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0026_mailrule_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaccount",
            name="password",
            field=models.CharField(max_length=3072, verbose_name="password"),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="expiration",
            field=models.DateTimeField(
                blank=True,
                help_text="The expiration date of the refresh token. ",
                null=True,
                verbose_name="expiration",
            ),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="account_type",
            field=models.PositiveIntegerField(
                choices=[(1, "IMAP"), (2, "Gmail OAuth"), (3, "Outlook OAuth")],
                default=1,
                verbose_name="account type",
            ),
        ),
        migrations.AddField(
            model_name="mailaccount",
            name="refresh_token",
            field=models.CharField(
                blank=True,
                help_text="The refresh token to use for token authentication e.g. with oauth2.",
                max_length=3072,
                null=True,
                verbose_name="refresh token",
            ),
        ),
    ]
