# Generated by Django 5.1.3 on 2024-11-24 12:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0028_alter_mailaccount_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="pdf_layout",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Text, then HTML"),
                    (2, "HTML, then text"),
                    (3, "HTML only"),
                    (4, "Text only"),
                ],
                default=1,
                verbose_name="pdf layout",
            ),
        ),
    ]
