# Generated by Django 5.1.3 on 2024-12-26 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless_mail", "0029_mailrule_pdf_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="remove_file_password",
            field=models.BooleanField(
                default=False,
                help_text="Try to remove password protection from attachments before consumption.",
                verbose_name="remove file password protection",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="file_password",
            field=models.CharField(
                blank=True,
                help_text="Password to use when removing protection from password-protected files.",
                max_length=256,
                null=True,
                verbose_name="file password",
            ),
        ),
    ]
