# Generated by Django 5.2.6 on 2025-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless_mail', '0029_mailrule_pdf_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrule',
            name='append_attachments',
            field=models.PositiveIntegerField(choices=[(0, 'System default'), (1, 'Do not append attachments.'), (2, 'Append processed attachments.')], default=0, help_text='Append processed attachments of the email to the email document.', verbose_name='append attachments'),
        ),
    ]
