autolabeler:
  - label: "bug"
    branch:
      - '/^fix/'
    title:
      - "/^fix/i"
      - "/^Bugfix/i"
  - label: "enhancement"
    branch:
      - '/^feature/'
    title:
      - "/^feature/i"
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
  - title: 'Notable Changes'
    labels:
      - 'notable'
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'deployment'
      - 'translation'
      - 'ci-cd'
  - title: 'Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: 'All App Changes'
    labels:
      - 'frontend'
      - 'backend'
    collapse-after: 1
include-labels:
  - 'enhancement'
  - 'bug'
  - 'chore'
  - 'deployment'
  - 'translation'
  - 'dependencies'
  - 'documentation'
  - 'frontend'
  - 'backend'
  - 'ci-cd'
  - 'breaking-change'
  - 'notable'
exclude-labels:
  - 'skip-changelog'
category-template: '### $TITLE'
change-template: '- $TITLE @$AUTHOR ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&#@'
template: |
  ## paperless-ngx $RESOLVED_VERSION

  $CHANGES
