#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash

cd ${PAPERLESS_SRC_DIR}

if [[ -n "${USER_IS_NON_ROOT}" ]]; then
	exec python3 manage.py document_consumer
else
	exec s6-setuidgid paperless python3 manage.py document_consumer
fi
