#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash

cd ${PAPERLESS_SRC_DIR}

if [[ -n "${USER_IS_NON_ROOT}" ]]; then
	exec /usr/local/bin/gunicorn -c /usr/src/paperless/gunicorn.conf.py paperless.asgi:application
else
	exec s6-setuidgid paperless /usr/local/bin/gunicorn -c /usr/src/paperless/gunicorn.conf.py paperless.asgi:application
fi
