# This Dockerfile compiles the frontend
# Inputs: None

FROM node:16-bullseye-slim AS compile-frontend

COPY ./src /src/src
COPY ./src-ui /src/src-ui

WORKDIR /src/src-ui
RUN set -eux \
  && npm update npm -g \
  && npm ci --omit=optional
RUN set -eux \
  && ./node_modules/.bin/ng build --configuration production
