name: Bug report
description: Something is not working
title: "[BUG] Concise description of the issue"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        ### âš ï¸ Please remember: issues are for *bugs*
        That is, something you believe affects every single user of Paperless-ngx, not just you. If you're not sure, start with one of the other options below.

        Also, note that **Paperless-ngx does not perform OCR or archive file creation itself**, those are handled by other tools. Problems with OCR or archive versions of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues
  - type: markdown
    attributes:
      value: |
        #### Have a question? ðŸ‘‰ [Start a new discussion](https://github.com/paperless-ngx/paperless-ngx/discussions/new) or [ask in chat](https://matrix.to/#/#paperlessngx:matrix.org).

        #### Before opening an issue, please double check:

        - [The troubleshooting documentation](https://docs.paperless-ngx.com/troubleshooting/).
        - [The installation instructions](https://docs.paperless-ngx.com/setup/#installation).
        - [Existing issues and discussions](https://github.com/paperless-ngx/paperless-ngx/search?q=&type=issues).
        - Disable any custom container initialization scripts, if using

        If you encounter issues while installing or configuring Paperless-ngx, please post in the ["Support" section of the discussions](https://github.com/paperless-ngx/paperless-ngx/discussions/new?category=support).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
      placeholder: |
        Currently Paperless does not work when...

        [Screenshot if applicable]
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Webserver logs
      description: Logs from the web server related to your issue.
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs_browser
    attributes:
      label: Browser logs
      description: Logs from the web browser related to your issue, if needed
      render: bash
  - type: input
    id: version
    attributes:
      label: Paperless-ngx version
      placeholder: e.g. 1.6.0
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Host OS of the machine running paperless-ngx. Please add the architecture (uname -m) if applicable.
      placeholder: e.g. Archlinux / Ubuntu 20.04 / Raspberry Pi `arm64`
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Docker - official image
        - Docker - linuxserver.io image
        - Bare metal
        - Other (please describe above)
      description: Note there are significant differences from the official image and linuxserver.io, please check if your issue is specific to the third-party image.
    validations:
      required: true
  - type: textarea
    id: system-status
    attributes:
      label: System status
      description: If available, copy & paste the system status output from Settings > System Status > Copy
      render: json
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser you are using, if relevant.
      placeholder: e.g. Chrome, Safari
  - type: textarea
    id: config-changes
    attributes:
      label: Configuration changes
      description: Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
  - type: checkboxes
    id: required-checks
    attributes:
      label: Please confirm the following
      options:
        - label: I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
          required: true
        - label: This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
          required: true
        - label: I have already searched for relevant existing issues and discussions before opening this report.
          required: true
        - label: I have updated the title field above with a concise description.
          required: true
