blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/datakit/datakit/discussions
    about: General questions or support for using DataKit.
  - name: 💬 Chat
    url: https://matrix.to/#/#paperlessngx:matrix.org
    about: Want to discuss DataKit with others? Check out our chat.
  - name: 🚀 Feature Request
    url: https://github.com/datakit/datakit/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" those that you like.
