# Generated by Django 4.1.10 on 2023-07-09 13:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSOGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_groups",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSO group",
                "verbose_name_plural": "SSO groups",
                "ordering": ("name",),
            },
        ),
    ]
