# Generated by Django 5.2.14 on 2026-06-04 15:30

import django.core.validators
from django.db import migrations
from django.db import models


def _create_singleton(apps, schema_editor):
    settings_model = apps.get_model("paperless", "ApplicationConfiguration")
    settings_model.objects.create()


class Migration(migrations.Migration):
    replaces = [
        ("paperless", "0001_initial"),
        ("paperless", "0002_applicationconfiguration_app_logo_and_more"),
        ("paperless", "0003_alter_applicationconfiguration_max_image_pixels"),
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
        ("paperless", "0005_applicationconfiguration_ai_enabled_and_more"),
        ("paperless", "0006_applicationconfiguration_barcode_tag_split"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "pdf"),
                            ("pdfa", "pdfa"),
                            ("pdfa-1", "pdfa-1"),
                            ("pdfa-2", "pdfa-2"),
                            ("pdfa-3", "pdfa-3"),
                        ],
                        max_length=8,
                        null=True,
                        verbose_name="Sets the output PDF type",
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Do OCR from page 1 to this value",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Do OCR using these languages",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("skip", "skip"),
                            ("redo", "redo"),
                            ("force", "force"),
                            ("skip_noarchive", "skip_noarchive"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Sets the OCR mode",
                    ),
                ),
                (
                    "skip_archive_file",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "never"),
                            ("with_text", "with_text"),
                            ("always", "always"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Controls the generation of an archive file",
                    ),
                ),
                (
                    "image_dpi",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sets image DPI fallback value",
                    ),
                ),
                (
                    "unpaper_clean",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clean", "clean"),
                            ("clean-final", "clean-final"),
                            ("none", "none"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Controls the unpaper cleaning",
                    ),
                ),
                (
                    "deskew",
                    models.BooleanField(null=True, verbose_name="Enables deskew"),
                ),
                (
                    "rotate_pages",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables page rotation",
                    ),
                ),
                (
                    "rotate_pages_threshold",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Sets the threshold for rotation of pages",
                    ),
                ),
                (
                    "max_image_pixels",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Sets the maximum image size for decompression",
                    ),
                ),
                (
                    "color_conversion_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LeaveColorUnchanged", "LeaveColorUnchanged"),
                            ("RGB", "RGB"),
                            ("UseDeviceIndependentColor", "UseDeviceIndependentColor"),
                            ("Gray", "Gray"),
                            ("CMYK", "CMYK"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Sets the Ghostscript color conversion strategy",
                    ),
                ),
                (
                    "user_args",
                    models.JSONField(
                        null=True,
                        verbose_name="Adds additional user arguments for OCRMyPDF",
                    ),
                ),
                (
                    "app_logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="logo/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "gif", "svg"],
                            ),
                        ],
                        verbose_name="Application logo",
                    ),
                ),
                (
                    "app_title",
                    models.CharField(
                        blank=True,
                        max_length=48,
                        null=True,
                        verbose_name="Application title",
                    ),
                ),
                (
                    "barcode_asn_prefix",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Sets the ASN barcode prefix",
                    ),
                ),
                (
                    "barcode_dpi",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sets the barcode DPI",
                    ),
                ),
                (
                    "barcode_enable_asn",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables ASN barcode",
                    ),
                ),
                (
                    "barcode_enable_tag",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables tag barcode",
                    ),
                ),
                (
                    "barcode_enable_tiff_support",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables barcode TIFF support",
                    ),
                ),
                (
                    "barcode_max_pages",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sets the maximum pages for barcode",
                    ),
                ),
                (
                    "barcode_retain_split_pages",
                    models.BooleanField(
                        null=True,
                        verbose_name="Retains split pages",
                    ),
                ),
                (
                    "barcode_string",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Sets the barcode string",
                    ),
                ),
                (
                    "barcode_tag_mapping",
                    models.JSONField(
                        null=True,
                        verbose_name="Sets the tag barcode mapping",
                    ),
                ),
                (
                    "barcode_upscale",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                        verbose_name="Sets the barcode upscale factor",
                    ),
                ),
                (
                    "barcodes_enabled",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables barcode scanning",
                    ),
                ),
                (
                    "ai_enabled",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="Enables AI features",
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Sets the LLM API key",
                    ),
                ),
                (
                    "llm_backend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai-like", "OpenAI-compatible"),
                            ("ollama", "Ollama"),
                        ],
                        max_length=128,
                        null=True,
                        verbose_name="Sets the LLM backend",
                    ),
                ),
                (
                    "llm_embedding_backend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai-like", "OpenAI-compatible"),
                            ("huggingface", "Huggingface"),
                        ],
                        max_length=128,
                        null=True,
                        verbose_name="Sets the LLM embedding backend",
                    ),
                ),
                (
                    "llm_embedding_model",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Sets the LLM embedding model",
                    ),
                ),
                (
                    "llm_endpoint",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Sets the LLM endpoint, optional",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Sets the LLM model",
                    ),
                ),
                (
                    "barcode_tag_split",
                    models.BooleanField(
                        null=True,
                        verbose_name="Enables splitting on tag barcodes",
                    ),
                ),
            ],
            options={
                "verbose_name": "paperless application settings",
            },
        ),
        migrations.RunPython(
            code=_create_singleton,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
