# Generated by Django 4.2.10 on 2024-03-04 17:30

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0002_applicationconfiguration_app_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="max_image_pixels",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Sets the maximum image size for decompression",
            ),
        ),
    ]
