# Generated by Django 5.1.7 on 2025-04-24 02:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0003_alter_applicationconfiguration_max_image_pixels"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ai_enabled",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Enables AI features",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("local", "Local")],
                max_length=32,
                null=True,
                verbose_name="Sets the LLM Embedding backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_model",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the LLM Embedding model",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_api_key",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Sets the LLM API key",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_backend",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("ollama", "Ollama")],
                max_length=32,
                null=True,
                verbose_name="Sets the LLM backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_model",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the LLM model",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_url",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Sets the LLM URL, optional",
            ),
        ),
    ]
