# Generated by Django 5.1.7 on 2025-04-02 19:21

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0003_alter_applicationconfiguration_max_image_pixels"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_asn_prefix",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the ASN barcode prefix",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_dpi",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the barcode DPI",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_asn",
            field=models.BooleanField(null=True, verbose_name="Enables ASN barcode"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_tag",
            field=models.BooleanField(null=True, verbose_name="Enables tag barcode"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_tiff_support",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables barcode TIFF support",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_max_pages",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the maximum pages for barcode",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_retain_split_pages",
            field=models.BooleanField(null=True, verbose_name="Retains split pages"),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_string",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the barcode string",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_tag_mapping",
            field=models.JSONField(
                null=True,
                verbose_name="Sets the tag barcode mapping",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_upscale",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1.0)],
                verbose_name="Sets the barcode upscale factor",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcodes_enabled",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables barcode scanning",
            ),
        ),
    ]
