# Generated by Django 5.1.8 on 2025-04-30 02:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ai_enabled",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Enables AI features",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_api_key",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Sets the LLM API key",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_backend",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("ollama", "Ollama")],
                max_length=32,
                verbose_name="Sets the LLM backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("huggingface", "Huggingface")],
                max_length=32,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_model",
            field=models.CharField(
                blank=True,
                max_length=32,
                verbose_name="Sets the LLM embedding model",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_model",
            field=models.CharField(
                blank=True,
                max_length=32,
                verbose_name="Sets the LLM model",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_endpoint",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Sets the LLM endpoint, optional",
            ),
        ),
    ]
