# Generated by Django 5.1.7 on 2025-12-15 21:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_tag_split",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables splitting on tag barcodes",
            ),
        ),
    ]
