# Generated by Django 5.2.9 on 2026-01-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0005_applicationconfiguration_ai_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the tenant', max_length=255, verbose_name='Tenant Name')),
                ('subdomain', models.CharField(db_index=True, help_text="Unique subdomain for this tenant (e.g., 'tenant-a')", max_length=63, unique=True, verbose_name='Subdomain')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and can be accessed', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['subdomain'],
            },
        ),
    ]
