# Generated by Django 5.2.11 on 2026-02-09 16:37

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_barcode_tag_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="barcode_dpi",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the barcode DPI",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="barcode_max_pages",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the maximum pages for barcode",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="image_dpi",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets image DPI fallback value",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="pages",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Do OCR from page 1 to this value",
            ),
        ),
    ]
