# Generated by Django 5.2.12 on 2026-03-26 20:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_optimize_integer_field_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationconfiguration",
            name="skip_archive_file",
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="archive_file_generation",
            field=models.CharField(
                blank=True,
                choices=[("auto", "auto"), ("always", "always"), ("never", "never")],
                max_length=8,
                null=True,
                verbose_name="Controls archive file generation",
            ),
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "auto"),
                    ("force", "force"),
                    ("redo", "redo"),
                    ("off", "off"),
                ],
                max_length=16,
                null=True,
                verbose_name="Sets the OCR mode",
            ),
        ),
    ]
