# Generated by Django 5.2.11 on 2026-02-23 17:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0007_optimize_integer_field_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_custom_field",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables custom field barcode",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_custom_field_mapping",
            field=models.JSONField(
                null=True,
                verbose_name="Sets the custom field barcode mapping",
            ),
        ),
    ]
