# Generated by Django 5.2.14 on 2026-06-04 15:19

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("paperless", "0009_alter_applicationconfiguration_options"),
        ("paperless", "0010_alter_applicationconfiguration_llm_embedding_backend"),
        ("paperless", "0011_applicationconfiguration_llm_embedding_chunk_size"),
        ("paperless", "0012_applicationconfiguration_llm_output_language"),
        ("paperless", "0013_applicationconfiguration_llm_request_timeout"),
    ]

    dependencies = [
        ("paperless", "0008_replace_skip_archive_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationconfiguration",
            options={
                "permissions": [
                    ("view_global_statistics", "Can view global object counts"),
                    ("view_system_monitoring", "Can view system status information"),
                ],
                "verbose_name": "paperless application settings",
            },
        ),
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai-like", "OpenAI-compatible"),
                    ("huggingface", "Huggingface"),
                    ("ollama", "Ollama"),
                ],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the LLM embedding endpoint, optional",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_chunk_size",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the LLM embedding chunk size",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_context_size",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the LLM context size",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_output_language",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the LLM output language",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_request_timeout",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the LLM request timeout in seconds",
            ),
        ),
    ]
