# Generated by Django 5.2.12 on 2026-04-07 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0008_replace_skip_archive_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationconfiguration",
            options={
                "permissions": [
                    ("view_global_statistics", "Can view global object counts"),
                    ("view_system_status", "Can view system status information"),
                ],
                "verbose_name": "paperless application settings",
            },
        ),
    ]
