# Generated by Django 5.2.6 on 2026-05-08 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0009_alter_applicationconfiguration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="llm_embedding_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai-like", "OpenAI-compatible"),
                    ("huggingface", "Huggingface"),
                    ("ollama", "Ollama"),
                ],
                max_length=128,
                null=True,
                verbose_name="Sets the LLM embedding backend",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the LLM embedding endpoint, optional",
            ),
        ),
    ]
