# Generated by Django 5.2.13 on 2026-05-08 19:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0009_alter_applicationconfiguration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the LLM embedding endpoint, optional",
            ),
        ),
    ]
