# Generated by Django 5.2.6 on 2026-05-31

from django.core.validators import MinValueValidator
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0010_alter_applicationconfiguration_llm_embedding_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_chunk_size",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[MinValueValidator(1)],
                verbose_name="Sets the LLM embedding chunk size",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_context_size",
            field=models.PositiveIntegerField(
                null=True,
                validators=[MinValueValidator(1)],
                verbose_name="Sets the LLM context size",
            ),
        ),
    ]
