# Generated by Django 5.2.7 on 2026-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0010_alter_prompt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='video_content_mode',
            field=models.CharField(blank=True, choices=[('transcript', 'transcript'), ('summary', 'summary'), ('both', 'both')], default='both', max_length=16, null=True, verbose_name='Video content mode'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='supplier',
            field=models.CharField(max_length=64, verbose_name='supplier'),
        ),
    ]
