# Generated by Django 5.2.6 on 2026-06-02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0011_applicationconfiguration_llm_embedding_chunk_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_output_language",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Sets the LLM output language",
            ),
        ),
    ]
