# Generated by Django 5.2.7 on 2026-09-30 08:23

from django.db import migrations
from django.db import models


def clear_migration_default(apps, schema_editor):
    """
    0011 stored the implicit default "both" on existing rows.
    Leave the field unset so PAPERLESS_VIDEO_CONTENT_MODE applies
    until an admin saves a value in the UI.
    """
    ApplicationConfiguration = apps.get_model("paperless", "ApplicationConfiguration")
    ApplicationConfiguration.objects.filter(video_content_mode="both").update(
        video_content_mode=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0011_aimodel_supplier_free_and_video_content_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationconfiguration",
            name="video_content_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transcript", "transcript"),
                    ("summary", "summary"),
                    ("both", "both"),
                ],
                max_length=16,
                null=True,
                verbose_name="Video content mode",
            ),
        ),
        migrations.RunPython(clear_migration_default, migrations.RunPython.noop),
    ]
