# Generated by Django 5.2.14 on 2026-06-14 14:22

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0012_applicationconfiguration_llm_output_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_request_timeout",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Sets the LLM request timeout in seconds",
            ),
        ),
    ]
