# Generated by Django 4.2.11 on 2025-02-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0012_remove_applicationconfiguration_api_ocr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='password_ocr',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Password ocr'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='username_ocr',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Username ocr'),
        ),
    ]
