# Generated by Django 5.2.16 on 2026-08-10 14:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0013_applicationconfiguration_llm_request_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="remote_ocr_api_key",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Sets the remote OCR API key",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="remote_ocr_endpoint",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sets the remote OCR endpoint",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="remote_ocr_engine",
            field=models.CharField(
                blank=True,
                choices=[("azureai", "Azure AI Document Intelligence")],
                max_length=32,
                null=True,
                verbose_name="Sets the remote OCR engine",
            ),
        ),
    ]
