# Generated by Django 5.2.16 on 2026-08-10 15:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0014_applicationconfiguration_remote_ocr_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="remote_ocr_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("always", "All supported documents"),
                    ("workflow_only", "Only when a workflow enables it"),
                ],
                max_length=32,
                null=True,
                verbose_name="Sets which documents are sent to the remote OCR engine",
            ),
        ),
    ]
