# Generated by Django 5.2.16 on 2026-07-18 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0014_account_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accountsessiongroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='llm_request_timeout',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sets the LLM timeout in seconds'),
        ),
    ]
