# Generated by Django 5.2.16 on 2026-08-31 13:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0015_applicationconfiguration_remote_ocr_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="ai_suggest_on_open",
            field=models.BooleanField(
                null=True,
                verbose_name="Request AI suggestions when opening inbox documents",
            ),
        ),
    ]
