# Generated by Django 5.2.16 on 2026-09-11 09:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0016_alter_applicationconfiguration_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="llm_embedding_api_key",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Sets the LLM embedding API key",
            ),
        ),
    ]
