# Generated by Django 5.2.16 on 2026-09-26 14:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0017_applicationconfiguration_llm_embedding_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_store_values",
            field=models.BooleanField(
                null=True,
                verbose_name="Stores the values of detected barcodes",
            ),
        ),
    ]
