# Generated by Django 4.2.7 on 2023-12-07 22:52

import django.core.validators
from django.db import migrations
from django.db import models


def _create_singleton(apps, schema_editor):
    settings_model = apps.get_model("paperless_tesseract", "OcrSettings")
    settings_model.objects.create()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OcrSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "output_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "pdf"),
                            ("pdfa", "pdfa"),
                            ("pdfa-1", "pdfa-1"),
                            ("pdfa-2", "pdfa-2"),
                            ("pdfa-3", "pdfa-3"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("skip", "skip"),
                            ("skip_noarchive", "skip_noarchive"),
                            ("redo", "redo"),
                            ("force", "force"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "skip_archive_file",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "never"),
                            ("with_text", "with_text"),
                            ("always", "always"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("image_dpi", models.PositiveIntegerField(null=True)),
                (
                    "unpaper_clean",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clean", "clean"),
                            ("clean-final", "clean-final"),
                            ("none", "none"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("deskew", models.BooleanField(null=True)),
                ("rotate_pages", models.BooleanField(null=True)),
                (
                    "rotate_pages_threshold",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_image_pixels",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000.0),
                        ],
                    ),
                ),
                (
                    "color_conversion_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LeaveColorUnchanged", "LeaveColorUnchanged"),
                            ("RGB", "RGB"),
                            ("UseDeviceIndependentColor", "UseDeviceIndependentColor"),
                            ("Gray", "Gray"),
                            ("CMYK", "CMYK"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("user_args", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ocr settings",
            },
        ),
        migrations.RunPython(
            code=_create_singleton,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
