#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash

declare -r log_prefix="[svc-flower]"

echo "${log_prefix} Checking if we should start flower..."

if [[ -n "${PAPERLESS_ENABLE_FLOWER}" ]]; then
	# Small delay to allow celery to be up first
	echo "${log_prefix} Starting flower in 5s"
	sleep 5
	cd ${PAPERLESS_SRC_DIR}

	if [[ -n "${USER_IS_NON_ROOT}" ]]; then
		exec /usr/local/bin/celery --app paperless flower --conf=${PAPERLESS_SRC_DIR}/paperless/flowerconfig.py
	else
		exec s6-setuidgid paperless /usr/local/bin/celery --app paperless flower --conf=${PAPERLESS_SRC_DIR}/paperless/flowerconfig.py
	fi

else
	echo "${log_prefix} Not starting flower"
	# https://skarnet.org/software/s6/s6-svc.html
	s6-svc -Od .
fi
