# Generated by Django 1.9 on 2015-12-26 13:16

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ("sender", "title")},
        ),
        migrations.AlterField(
            model_name="document",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
            ),
        ),
    ]
