# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('sender', 'title')},
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
