# Generated by Django 5.2.9 on 2026-01-20 20:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="order"),
        ),
    ]
