# Generated by Django 5.2.14 on 2026-06-04 15:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("documents", "0003_remove_document_storage_type"),
        ("documents", "0004_workflowtrigger_filter_has_any_correspondents_and_more"),
        ("documents", "0005_alter_document_checksum_unique"),
    ]

    dependencies = [
        ("documents", "0002_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="storage_type",
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_correspondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_correspondent",
                to="documents.correspondent",
                verbose_name="has one of these correspondents",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_document_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_document_type",
                to="documents.documenttype",
                verbose_name="has one of these document types",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_storage_paths",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_storage_path",
                to="documents.storagepath",
                verbose_name="has one of these storage paths",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                editable=False,
                help_text="The checksum of the original document.",
                max_length=32,
                verbose_name="checksum",
            ),
        ),
    ]
