# Generated by Django 5.2.9 on 2026-01-24 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="storage_type",
        ),
    ]
