# Generated by Django 5.2.7 on 2025-12-17 22:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_remove_document_storage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_correspondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_correspondent",
                to="documents.correspondent",
                verbose_name="has one of these correspondents",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_document_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_document_type",
                to="documents.documenttype",
                verbose_name="has one of these document types",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_any_storage_paths",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_any_storage_path",
                to="documents.storagepath",
                verbose_name="has one of these storage paths",
            ),
        ),
    ]
