# Generated by Django 5.2.14 on 2026-06-04 15:31

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("documents", "0008_workflowaction_passwords_alter_workflowaction_type"),
        ("documents", "0009_alter_document_content_length"),
        ("documents", "0010_optimize_integer_field_sizes"),
        ("documents", "0011_alter_workflowaction_type"),
        ("documents", "0012_document_root_document"),
    ]

    dependencies = [
        ("documents", "0007_sharelinkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="passwords",
            field=models.JSONField(
                blank=True,
                help_text="Passwords to try when removing PDF protection. Separate with commas or new lines.",
                null=True,
                verbose_name="passwords",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content_length",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Length("content"),
                help_text="Length of the content field in characters. Automatically maintained by the database for faster statistics computation.",
                output_field=models.PositiveIntegerField(default=0),
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="correspondent",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="savedviewfilterrule",
            name="rule_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "title contains"),
                    (1, "content contains"),
                    (2, "ASN is"),
                    (3, "correspondent is"),
                    (4, "document type is"),
                    (5, "is in inbox"),
                    (6, "has tag"),
                    (7, "has any tag"),
                    (8, "created before"),
                    (9, "created after"),
                    (10, "created year is"),
                    (11, "created month is"),
                    (12, "created day is"),
                    (13, "added before"),
                    (14, "added after"),
                    (15, "modified before"),
                    (16, "modified after"),
                    (17, "does not have tag"),
                    (18, "does not have ASN"),
                    (19, "title or content contains"),
                    (20, "fulltext query"),
                    (21, "more like this"),
                    (22, "has tags in"),
                    (23, "ASN greater than"),
                    (24, "ASN less than"),
                    (25, "storage path is"),
                    (26, "has correspondent in"),
                    (27, "does not have correspondent in"),
                    (28, "has document type in"),
                    (29, "does not have document type in"),
                    (30, "has storage path in"),
                    (31, "does not have storage path in"),
                    (32, "owner is"),
                    (33, "has owner in"),
                    (34, "does not have owner"),
                    (35, "does not have owner in"),
                    (36, "has custom field value"),
                    (37, "is shared by me"),
                    (38, "has custom fields"),
                    (39, "has custom field in"),
                    (40, "does not have custom field in"),
                    (41, "does not have custom field"),
                    (42, "custom fields query"),
                    (43, "created to"),
                    (44, "created from"),
                    (45, "added to"),
                    (46, "added from"),
                    (47, "mime type is"),
                ],
                verbose_name="rule type",
            ),
        ),
        migrations.AlterField(
            model_name="storagepath",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                ],
                null=True,
                verbose_name="workflow trigger type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                ],
                default=0,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                ],
                default=1,
                verbose_name="Workflow Trigger Type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                    (6, "Move to trash"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="root_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.document",
                verbose_name="root document for this version",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version_label",
            field=models.CharField(
                blank=True,
                help_text="Optional short label for a document version.",
                max_length=64,
                null=True,
                verbose_name="version label",
            ),
        ),
    ]
