# Generated by Django 5.2.7 on 2025-12-29 03:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_sharelinkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="passwords",
            field=models.JSONField(
                blank=True,
                help_text="Passwords to try when removing PDF protection. Separate with commas or new lines.",
                null=True,
                verbose_name="passwords",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
    ]
