# Generated by Django 5.2.11 on 2026-02-07 19:06

import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_workflowaction_passwords_alter_workflowaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content_length",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Length("content"),
                help_text="Length of the content field in characters. Automatically maintained by the database for faster statistics computation.",
                output_field=models.PositiveIntegerField(default=0),
                serialize=False,
            ),
        ),
    ]
