# Generated by Django 5.2.9 on 2026-01-24 14:55

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_workflowaction_passwords_alter_workflowaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowActionDeletion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Deletion"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="deletion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action",
                to="documents.workflowactiondeletion",
                verbose_name="delete",
            ),
        ),
    ]
