# Generated by Django 5.2.11 on 2026-02-09 16:37

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_alter_document_content_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correspondent",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="savedviewfilterrule",
            name="rule_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "title contains"),
                    (1, "content contains"),
                    (2, "ASN is"),
                    (3, "correspondent is"),
                    (4, "document type is"),
                    (5, "is in inbox"),
                    (6, "has tag"),
                    (7, "has any tag"),
                    (8, "created before"),
                    (9, "created after"),
                    (10, "created year is"),
                    (11, "created month is"),
                    (12, "created day is"),
                    (13, "added before"),
                    (14, "added after"),
                    (15, "modified before"),
                    (16, "modified after"),
                    (17, "does not have tag"),
                    (18, "does not have ASN"),
                    (19, "title or content contains"),
                    (20, "fulltext query"),
                    (21, "more like this"),
                    (22, "has tags in"),
                    (23, "ASN greater than"),
                    (24, "ASN less than"),
                    (25, "storage path is"),
                    (26, "has correspondent in"),
                    (27, "does not have correspondent in"),
                    (28, "has document type in"),
                    (29, "does not have document type in"),
                    (30, "has storage path in"),
                    (31, "does not have storage path in"),
                    (32, "owner is"),
                    (33, "has owner in"),
                    (34, "does not have owner"),
                    (35, "does not have owner in"),
                    (36, "has custom field value"),
                    (37, "is shared by me"),
                    (38, "has custom fields"),
                    (39, "has custom field in"),
                    (40, "does not have custom field in"),
                    (41, "does not have custom field"),
                    (42, "custom fields query"),
                    (43, "created to"),
                    (44, "created from"),
                    (45, "added to"),
                    (46, "added from"),
                    (47, "mime type is"),
                ],
                verbose_name="rule type",
            ),
        ),
        migrations.AlterField(
            model_name="storagepath",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                    (6, "Automatic"),
                ],
                default=1,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                ],
                null=True,
                verbose_name="workflow trigger type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="matching_algorithm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                ],
                default=0,
                verbose_name="matching algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="schedule_offset_days",
            field=models.SmallIntegerField(
                default=0,
                help_text="The number of days to offset the schedule trigger by.",
                verbose_name="schedule offset days",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="schedule_recurring_interval_days",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="The number of days between recurring schedule triggers.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="schedule recurring delay in days",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                ],
                default=1,
                verbose_name="Workflow Trigger Type",
            ),
        ),
    ]
