# Generated by Django 5.2.11 on 2026-02-20 22:05

from django.db import migrations
from django.db import models

DASHBOARD_VIEWS_VISIBLE_IDS_KEY = (
    "general-settings:saved-views:dashboard-views-visible-ids"
)
SIDEBAR_VIEWS_VISIBLE_IDS_KEY = "general-settings:saved-views:sidebar-views-visible-ids"


def _parse_visible_ids(raw_value) -> set[int]:
    if not isinstance(raw_value, list):
        return set()

    parsed_ids = set()
    for raw_id in raw_value:
        if isinstance(raw_id, int):
            parsed_ids.add(raw_id)
        elif isinstance(raw_id, str) and raw_id.isdigit():
            parsed_ids.add(int(raw_id))
    return parsed_ids


def _set_default_visibility_ids(apps, schema_editor):
    SavedView = apps.get_model("documents", "SavedView")
    UiSettings = apps.get_model("documents", "UiSettings")
    User = apps.get_model("auth", "User")

    dashboard_visible_ids = list(
        SavedView.objects.filter(show_on_dashboard=True).values_list("id", flat=True),
    )
    sidebar_visible_ids = list(
        SavedView.objects.filter(show_in_sidebar=True).values_list("id", flat=True),
    )

    for user in User.objects.all():
        ui_settings, _ = UiSettings.objects.get_or_create(
            user=user,
            defaults={"settings": {}},
        )
        current_settings = ui_settings.settings
        if not isinstance(current_settings, dict):
            current_settings = {}

        changed = False

        if current_settings.get(DASHBOARD_VIEWS_VISIBLE_IDS_KEY) is None:
            current_settings[DASHBOARD_VIEWS_VISIBLE_IDS_KEY] = dashboard_visible_ids
            changed = True
        if current_settings.get(SIDEBAR_VIEWS_VISIBLE_IDS_KEY) is None:
            current_settings[SIDEBAR_VIEWS_VISIBLE_IDS_KEY] = sidebar_visible_ids
            changed = True

        if changed:
            ui_settings.settings = current_settings
            ui_settings.save(update_fields=["settings"])


def _restore_visibility_fields(apps, schema_editor):
    SavedView = apps.get_model("documents", "SavedView")
    UiSettings = apps.get_model("documents", "UiSettings")

    dashboard_visible_ids = set()
    sidebar_visible_ids = set()

    for ui_settings in UiSettings.objects.all():
        current_settings = ui_settings.settings
        if not isinstance(current_settings, dict):
            continue
        dashboard_visible_ids.update(
            _parse_visible_ids(current_settings.get(DASHBOARD_VIEWS_VISIBLE_IDS_KEY)),
        )
        sidebar_visible_ids.update(
            _parse_visible_ids(current_settings.get(SIDEBAR_VIEWS_VISIBLE_IDS_KEY)),
        )

    SavedView.objects.update(show_on_dashboard=False, show_in_sidebar=False)
    if dashboard_visible_ids:
        SavedView.objects.filter(id__in=dashboard_visible_ids).update(
            show_on_dashboard=True,
        )
    if sidebar_visible_ids:
        SavedView.objects.filter(id__in=sidebar_visible_ids).update(
            show_in_sidebar=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_optimize_integer_field_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedview",
            name="show_on_dashboard",
            field=models.BooleanField(default=False, verbose_name="show on dashboard"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="show_in_sidebar",
            field=models.BooleanField(default=False, verbose_name="show in sidebar"),
        ),
        migrations.RunPython(
            _set_default_visibility_ids,
            reverse_code=_restore_visibility_fields,
        ),
        migrations.RemoveField(
            model_name="savedview",
            name="show_on_dashboard",
        ),
        migrations.RemoveField(
            model_name="savedview",
            name="show_in_sidebar",
        ),
    ]
