# Generated by Django 5.2.11 on 2026-02-14 19:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_optimize_integer_field_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                    (6, "Move to trash"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
    ]
