# Generated by Codex on 2026-02-10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_document_head_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="version_label",
            field=models.CharField(
                blank=True,
                help_text="Optional short label for a document version.",
                max_length=64,
                null=True,
                verbose_name="version label",
            ),
        ),
    ]
