# Generated by Django 5.1.6 on 2025-02-26 17:08

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0012_alter_workflowaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="root_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.document",
                verbose_name="root document for this version",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version_label",
            field=models.CharField(
                blank=True,
                help_text="Optional short label for a document version.",
                max_length=64,
                null=True,
                verbose_name="version label",
            ),
        ),
    ]
