# Generated by Django 5.2.7 on 2026-03-02 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0013_document_root_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtrigger",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                    (5, "Version Added"),
                ],
                default=1,
                verbose_name="Workflow Trigger Type",
            ),
        ),
    ]
