# Generated by Django 1.10.5 on 2017-03-25 15:58

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0015_add_insensitive_to_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(
                blank=True,
                db_index=("mysql" not in settings.DATABASES["default"]["ENGINE"]),
                help_text="The raw, text-only data of the document.  This field is primarily used for searching.",
            ),
        ),
    ]
