# Generated by Django 1.10.5 on 2017-07-15 17:12

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0017_auto_20170512_0507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="correspondent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.Correspondent",
            ),
        ),
    ]
