# Generated by Django 1.10.5 on 2017-07-15 17:12

from django.contrib.auth.models import User
from django.db import migrations


def forwards_func(apps, schema_editor):
    User.objects.create(username="consumer")


def reverse_func(apps, schema_editor):
    User.objects.get(username="consumer").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_auto_20170715_1712"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
