# Generated by Django 5.2.12 on 2026-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_saved_view_simple_search_rules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-created",),
                "permissions": [
                    ("view_global_statistics", "Can view global object counts"),
                    ("view_system_status", "Can view system status information"),
                ],
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
    ]
