# Generated by Django 5.2.12 on 2026-04-07 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_saved_view_simple_search_rules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("-created",),
                "permissions": [
                    (
                        "can_view_statistics",
                        "Can view system statistics and object counts",
                    ),
                ],
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
    ]
