# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='storage_type',
            field=models.CharField(choices=[('unencrypted', 'Unencrypted'), ('gpg', 'Encrypted with GNU Privacy Guard')], default='unencrypted', editable=False, max_length=11),
        ),
    ]
