# Generated by Django 1.11.10 on 2018-02-04 13:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0020_document_added"),
    ]

    operations = [
        # Add the field with the default GPG-encrypted value
        migrations.AddField(
            model_name="document",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("unencrypted", "Unencrypted"),
                    ("gpg", "Encrypted with GNU Privacy Guard"),
                ],
                default="gpg",
                editable=False,
                max_length=11,
            ),
        ),
        # Now that the field is added, change the default to unencrypted
        migrations.AlterField(
            model_name="document",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("unencrypted", "Unencrypted"),
                    ("gpg", "Encrypted with GNU Privacy Guard"),
                ],
                default="unencrypted",
                editable=False,
                max_length=11,
            ),
        ),
    ]
