# Generated by Django 5.2.11 on 2026-05-19 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0020_drop_celery_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="order",
            field=models.IntegerField(default=0, verbose_name="order"),
        ),
    ]
