# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_storage_type'),
    ]

    operations = [

        migrations.AddField(
            model_name='document',
            name='archive_serial_number',
            field=models.IntegerField(unique=True, blank=True, null=True, db_index=True),
        ),

        migrations.AddField(
            model_name='tag',
            name='is_inbox_tag',
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name='tag',
            name='is_archived_tag',
            field=models.BooleanField(default=False),
        ),

    ]
