# Generated by Django 2.0.7 on 2018-07-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archive_serial_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='The position of this document in your physical document archive.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_archived_tag',
            field=models.BooleanField(default=False, help_text='Marks this tag as an archive tag: All documents tagged with archive tags will never be modified automatically (i.e., modifying tags by matching rules)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_inbox_tag',
            field=models.BooleanField(default=False, help_text='Marks this tag as an inbox tag: All newly consumed documents will be tagged with inbox tags.'),
        ),
    ]
