# Generated by Django 5.2.16 on 2026-07-20 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_widen_workflow_integer_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="archive_serial_number",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="The position of this document in your physical document archive.",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(4294967295),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="archive serial number",
            ),
        ),
        migrations.CreateModel(
            name="NamedCounter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "named counter",
                "verbose_name_plural": "named counters",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="named_counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.namedcounter",
                verbose_name="named counter",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("named_counter__isnull", True)),
                fields=("archive_serial_number",),
                name="documents_document_asn_unique_no_counter",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("named_counter__isnull", False)),
                fields=("archive_serial_number", "named_counter"),
                name="documents_document_asn_unique_per_counter",
            ),
        ),
    ]
