from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_add_perf_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="icon",
            field=models.CharField(
                choices=[
                    ("archive", "Archive"),
                    ("bank", "Bank"),
                    ("basket", "Basket"),
                    ("bell", "Bell"),
                    ("bookmark", "Bookmark"),
                    ("boxes", "Boxes"),
                    ("briefcase", "Briefcase"),
                    ("building", "Building"),
                    ("calculator", "Calculator"),
                    ("calendar", "Calendar"),
                    ("camera", "Camera"),
                    ("card-checklist", "Checklist"),
                    ("cash", "Cash"),
                    ("chat-left-text", "Chat"),
                    ("check-circle", "Check"),
                    ("clipboard", "Clipboard"),
                    ("clock-history", "Clock"),
                    ("credit-card", "Credit card"),
                    ("download", "Download"),
                    ("envelope", "Envelope"),
                    ("exclamation-triangle", "Warning"),
                    ("file-earmark", "File"),
                    ("file-earmark-check", "Checked file"),
                    ("file-earmark-lock", "Locked file"),
                    ("file-earmark-medical", "Medical file"),
                    ("file-earmark-person", "Person file"),
                    ("file-earmark-spreadsheet", "Spreadsheet"),
                    ("file-text", "Text file"),
                    ("files", "Files"),
                    ("folder", "Folder"),
                    ("funnel", "Filter"),
                    ("gear", "Gear"),
                    ("globe2", "Globe"),
                    ("hash", "Hash"),
                    ("heart", "Heart"),
                    ("house", "House"),
                    ("inbox", "Inbox"),
                    ("journals", "Journals"),
                    ("list-task", "Task list"),
                    ("newspaper", "Newspaper"),
                    ("paperclip", "Attachment"),
                    ("people", "People"),
                    ("person", "Person"),
                    ("printer", "Printer"),
                    ("receipt", "Receipt"),
                    ("safe", "Safe"),
                    ("search", "Search"),
                    ("send", "Send"),
                    ("shop", "Shop"),
                    ("stack", "Stack"),
                    ("stars", "Stars"),
                    ("tag", "Tag"),
                    ("tags", "Tags"),
                    ("telephone", "Telephone"),
                    ("truck", "Truck"),
                    ("upc-scan", "Barcode"),
                    ("wallet2", "Wallet"),
                ],
                default="funnel",
                max_length=64,
                verbose_name="icon",
            ),
        ),
    ]
