# Generated by Django 5.2.16 on 2026-08-10 17:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_add_perf_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                    (6, "Move to trash"),
                    (7, "Remote OCR"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
    ]
