# Generated by Django 5.2.16 on 2026-08-18 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.auth.models import User
from django.db import migrations
from django.db import models


def grant_export_permissions(apps, schema_editor):
    # Ensure newly introduced permissions are created for all apps
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    # Users and groups that can manage workflows also get to manage the export
    # targets those workflows deliver to, and to export a document on demand.
    add_workflow_perm = Permission.objects.filter(codename="add_workflow").first()
    export_manage_permissions = list(
        Permission.objects.filter(codename__contains="exporttarget"),
    ) + list(Permission.objects.filter(codename="add_exportrecord"))

    users = User.objects.filter(user_permissions=add_workflow_perm).distinct()
    for user in users:
        user.user_permissions.add(*export_manage_permissions)

    groups = Group.objects.filter(permissions=add_workflow_perm).distinct()
    for group in groups:
        group.permissions.add(*export_manage_permissions)

    # Anyone who can view documents can view their export history.
    view_document_perm = Permission.objects.filter(codename="view_document").first()
    view_export_record_perm = Permission.objects.filter(
        codename="view_exportrecord",
    ).first()

    if view_export_record_perm is not None:
        users = User.objects.filter(user_permissions=view_document_perm).distinct()
        for user in users:
            user.user_permissions.add(view_export_record_perm)

        groups = Group.objects.filter(permissions=view_document_perm).distinct()
        for group in groups:
            group.permissions.add(view_export_record_perm)


def revoke_export_permissions(apps, schema_editor):
    export_permissions = Permission.objects.filter(
        models.Q(codename__contains="exporttarget")
        | models.Q(codename__contains="exportrecord"),
    )
    for user in User.objects.all():
        user.user_permissions.remove(*export_permissions)
    for group in Group.objects.all():
        group.permissions.remove(*export_permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0023_savedview_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperlesstask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("consume_file", "Consume File"),
                    ("train_classifier", "Train Classifier"),
                    ("sanity_check", "Sanity Check"),
                    ("index_optimize", "Index Optimize"),
                    ("mail_fetch", "Mail Fetch"),
                    ("llm_index", "LLM Index"),
                    ("empty_trash", "Empty Trash"),
                    ("check_workflows", "Check Workflows"),
                    ("bulk_update", "Bulk Update"),
                    ("reprocess_document", "Reprocess Document"),
                    ("build_share_link", "Build Share Link"),
                    ("bulk_delete", "Bulk Delete"),
                    ("export_document", "Export Document"),
                ],
                db_index=True,
                help_text="The kind of work being performed",
                max_length=50,
                verbose_name="Task Type",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assignment"),
                    (2, "Removal"),
                    (3, "Email"),
                    (4, "Webhook"),
                    (5, "Password removal"),
                    (6, "Move to trash"),
                    (7, "Export"),
                ],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
        migrations.CreateModel(
            name="ExportTarget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("s3", "S3"), ("sftp", "SFTP"), ("local", "Local")],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret destination settings. S3: bucket, prefix, endpoint, region, storage class. SFTP: host, port, path, host key. Local: path.",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "access_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 access key or SFTP username.",
                        max_length=256,
                        null=True,
                        verbose_name="access key",
                    ),
                ),
                (
                    "secret_key",
                    models.TextField(
                        blank=True,
                        help_text="S3 secret key, or SFTP password or key passphrase.",
                        null=True,
                        verbose_name="secret key",
                    ),
                ),
                (
                    "private_key",
                    models.TextField(
                        blank=True,
                        help_text="SFTP private key for key authentication.",
                        null=True,
                        verbose_name="private key",
                    ),
                ),
                (
                    "passphrase",
                    models.TextField(
                        blank=True,
                        help_text="Reserved for client-side encryption of exports. Not used yet: exports are currently written unencrypted.",
                        null=True,
                        verbose_name="passphrase",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="S3 only: sets an Object Lock RetainUntilDate this many days in the future on every delivered object. The lock mode is configured on the bucket, not here.",
                        null=True,
                        verbose_name="retention days",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "export target",
                "verbose_name_plural": "export targets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WorkflowActionExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_original",
                    models.BooleanField(
                        default=True,
                        verbose_name="include original file",
                    ),
                ),
                (
                    "include_archive",
                    models.BooleanField(
                        default=False,
                        verbose_name="include archive file",
                    ),
                ),
                (
                    "write_metadata_sidecar",
                    models.BooleanField(
                        default=True,
                        help_text="Write a .metadata.json file with the document's metadata next to the exported file.",
                        verbose_name="write metadata sidecar",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional path and filename for exported files, overriding the document's filename. Works like a storage path, e.g. {{ created_year }}/{{ title }}; the file extension is appended automatically. If empty, files are named exactly as in the media directory.",
                        max_length=1024,
                        verbose_name="path",
                    ),
                ),
                (
                    "on_conflict",
                    models.CharField(
                        choices=[
                            ("overwrite", "Overwrite existing"),
                            ("skip", "Skip if exists"),
                            ("suffix", "Keep both (add suffix)"),
                        ],
                        default="overwrite",
                        help_text="What to do when the destination already has an object under the same name.",
                        max_length=16,
                        verbose_name="if file exists at destination",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_actions",
                        to="documents.exporttarget",
                        verbose_name="export target",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_pk",
                    models.IntegerField(db_index=True, verbose_name="document id"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "object_key",
                    models.TextField(
                        blank=True,
                        help_text="The key or path actually written at the destination.",
                        verbose_name="object key",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the delivered file.",
                        max_length=64,
                        verbose_name="checksum",
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="size in bytes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="finished at",
                    ),
                ),
                (
                    "last_error",
                    models.JSONField(blank=True, null=True, verbose_name="last error"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_records",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="documents.exporttarget",
                        verbose_name="export target",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="documents.workflowactionexport",
                        verbose_name="workflow action",
                    ),
                ),
            ],
            options={
                "verbose_name": "export record",
                "verbose_name_plural": "export records",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="export",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action",
                to="documents.workflowactionexport",
                verbose_name="export",
            ),
        ),
        migrations.RunPython(
            grant_export_permissions,
            reverse_code=revoke_export_permissions,
        ),
    ]
