# Generated by Django 5.2.16 on 2026-08-28 17:13

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_workflowaction_apply_ai_suggestions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["root_document", "version_index", "id"],
                name="doc_root_version_id_idx",
            ),
        ),
    ]
