# Generated by Django 5.2.16 on 2026-09-30 23:01

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0026_alter_document_archive_checksum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBarcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        help_text="Page of the original file, starting at 1",
                        verbose_name="page",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("Codabar", "Codabar"),
                            ("Code39", "Code 39"),
                            ("Code39Std", "Code 39 Standard"),
                            ("Code39Ext", "Code 39 Extended"),
                            ("Code32", "Code 32"),
                            ("PZN", "Pharmazentralnummer"),
                            ("Code93", "Code 93"),
                            ("Code128", "Code 128"),
                            ("ITF", "ITF"),
                            ("ITF14", "ITF-14"),
                            ("DataBar", "DataBar"),
                            ("DataBarOmni", "DataBar Omni"),
                            ("DataBarStk", "DataBar Stacked"),
                            ("DataBarStkOmni", "DataBar Stacked Omni"),
                            ("DataBarLtd", "DataBar Limited"),
                            ("DataBarExp", "DataBar Expanded"),
                            ("DataBarExpStk", "DataBar Expanded Stacked"),
                            ("EANUPC", "EAN/UPC"),
                            ("EAN13", "EAN-13"),
                            ("EAN8", "EAN-8"),
                            ("EAN5", "EAN-5"),
                            ("EAN2", "EAN-2"),
                            ("ISBN", "ISBN"),
                            ("UPCA", "UPC-A"),
                            ("UPCE", "UPC-E"),
                            ("Telepen", "Telepen"),
                            ("TelepenAlpha", "Telepen Alpha"),
                            ("TelepenNumeric", "Telepen Numeric"),
                            ("OtherBarcode", "Other barcode"),
                            ("DXFilmEdge", "DX Film Edge"),
                            ("PDF417", "PDF417"),
                            ("CompactPDF417", "Compact PDF417"),
                            ("MicroPDF417", "MicroPDF417"),
                            ("Aztec", "Aztec"),
                            ("AztecCode", "Aztec Code"),
                            ("AztecRune", "Aztec Rune"),
                            ("QRCode", "QR Code"),
                            ("QRCodeModel1", "QR Code Model 1"),
                            ("QRCodeModel2", "QR Code Model 2"),
                            ("MicroQRCode", "Micro QR Code"),
                            ("RMQRCode", "rMQR Code"),
                            ("DataMatrix", "Data Matrix"),
                            ("MaxiCode", "MaxiCode"),
                        ],
                        max_length=32,
                        verbose_name="format",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document barcode",
                "verbose_name_plural": "document barcodes",
                "ordering": ("page", "id"),
            },
        ),
    ]
