# Generated by Django 5.2.16 on 2026-09-26 14:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0026_alter_document_archive_checksum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentBarcode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        help_text="Page of the original file, starting at 1",
                        verbose_name="page",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
                (
                    "format",
                    models.CharField(blank=True, max_length=64, verbose_name="format"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document barcode",
                "verbose_name_plural": "document barcodes",
                "ordering": ("page", "id"),
            },
        ),
    ]
