# Generated by Django 5.2.17 on 2026-09-30 14:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0027_customfield_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="ai_suggestion_custom_fields",
            field=models.JSONField(blank=True, help_text="Which custom fields to apply AI-suggested values to (list of custom field IDs).", null=True, verbose_name="AI suggestion custom fields"),
        ),
    ]
