# Generated by Django 3.1.3 on 2020-11-09 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1000_update_paperless_all"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
