# Generated by Django 3.1.3 on 2020-11-09 16:36

from django.db import migrations
from django.db.migrations import RunPython
from django_q.models import Schedule
from django_q.tasks import schedule


def add_schedules(apps, schema_editor):
    schedule('documents.tasks.train_classifier', name="Train the classifier", schedule_type=Schedule.HOURLY)
    schedule('documents.tasks.index_optimize', name="Optimize the index", schedule_type=Schedule.DAILY)


def remove_schedules(apps, schema_editor):
    Schedule.objects.filter(func='documents.tasks.train_classifier').delete()
    Schedule.objects.filter(func='documents.tasks.index_optimize').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1000_update_paperless_all'),
        ('django_q', '0013_task_attempt_count'),
    ]

    operations = [
        RunPython(add_schedules, remove_schedules)
    ]
