# Generated by Django 3.1.3 on 2020-11-20 11:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1002_auto_20201111_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mime_type",
            field=models.CharField(default="-", editable=False, max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        # This operation is here so that we can revert the entire migration:
        # By allowing this field to be blank and null, we can revert the
        # remove operation further down and the database won't complain about
        # NOT NULL violations.
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("png", "PNG"),
                    ("jpg", "JPG"),
                    ("gif", "GIF"),
                    ("tiff", "TIFF"),
                    ("txt", "TXT"),
                    ("csv", "CSV"),
                    ("md", "MD"),
                ],
                editable=False,
                max_length=4,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="document",
            name="file_type",
        ),
    ]
