# Generated by Django 3.1.3 on 2020-11-25 14:53

from django.db import migrations
from django.db.migrations import RunPython


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1003_mime_types"),
    ]

    operations = [RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
