# Generated by Django 3.1.2 on 2020-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1003_auto_20201028_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='The raw, text-only data of the document. This field is primarily used for searching.'),
        ),
    ]
