# Generated by Django 3.1.2 on 2020-11-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1004_auto_20201029_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='log',
            name='modified',
        ),
        migrations.AlterField(
            model_name='log',
            name='group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
