# Generated by Django 3.1.4 on 2020-12-08 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1005_checksums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correspondent",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="documenttype",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
