# Generated by Django 3.1.4 on 2020-12-16 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1008_auto_20201216_1736"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correspondent",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="savedview",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
    ]
