# Generated by Django 4.0.3 on 2022-04-01 22:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1017_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedviewfilterrule",
            name="value",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="value",
            ),
        ),
    ]
