# Generated by Django 4.0.4 on 2022-07-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1019_category_correspondent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
