# Generated by Django 4.0.4 on 2022-05-18 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1019_storagepath_document_storage_path"),
        ("documents", "1019_uisettings"),
    ]

    operations = []
