# Generated by Django 4.0.6 on 2022-08-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1023_add_comments"),
        ("documents", "1023_document_original_filename"),
    ]

    operations = []
