# Generated by Django 4.0.6 on 2022-07-25 06:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1023_add_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(
                default=None,
                editable=False,
                help_text="The original name of the file when it was uploaded",
                max_length=1024,
                null=True,
                verbose_name="original filename",
            ),
        ),
    ]
