# Generated by Django 4.0.7 on 2022-09-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1025_alter_savedviewfilterrule_rule_type"),
    ]

    # Manual SQL commands to drop the django_q related tables
    # if they exist
    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS django_q_ormq", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS django_q_schedule", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS django_q_task", reverse_sql=migrations.RunSQL.noop
        ),
    ]
