# Generated by Django 4.1.3 on 2022-11-22 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1027_remove_paperlesstask_attempted_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperlesstask",
            name="task_args",
        ),
        migrations.RemoveField(
            model_name="paperlesstask",
            name="task_kwargs",
        ),
    ]
