# Generated by Django 4.1.5 on 2023-02-03 21:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1029_alter_document_archive_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperlesstask",
            name="task_file_name",
            field=models.CharField(
                help_text="Name of the file which the Task was run for",
                max_length=255,
                null=True,
                verbose_name="Task Filename",
            ),
        ),
    ]
