# Generated by Django 4.2.7 on 2023-11-30 14:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1040_customfield_customfieldinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumptiontemplate",
            name="sources",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(1, "Consume Folder"), (2, "Api Upload"), (3, "Mail Fetch")],
                default="1,2,3",
                max_length=5,
            ),
        ),
    ]
