# Generated by Django 4.2.7 on 2023-11-30 17:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1041_alter_consumptiontemplate_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptiontemplate",
            name="assign_custom_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="documents.customfield",
                verbose_name="assign these custom fields",
            ),
        ),
    ]
