# Generated by Django 4.2.8 on 2023-12-29 15:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1043_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptiontemplate",
            name="skip_inbox",
            field=models.BooleanField(
                default=False,
                verbose_name="Skip assigning inbox tag(s)",
            ),
        ),
    ]
