# Generated by Django 4.2.10 on 2024-02-22 03:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1044_workflow_workflowaction_workflowtrigger_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfieldinstance",
            name="value_monetary",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
