# Generated by Django 4.2.11 on 2024-04-11 18:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1046_workflowaction_remove_all_correspondents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="translation",
            field=models.TextField(
                blank=True,
                help_text="The translated version of the content field. This field can also be used for searching.",
                verbose_name="translation",
            ),
        ),
    ]
