# Generated by Django 4.2.11 on 2024-04-13 21:19

import secrets
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations


def delete_anonymous_user(apps, schema_editor):
    User.objects.get(username="AnonymousUser").delete()


def create_anonymous_user(apps, schema_editor):
    randomPassword = ''.join(secrets.choice('abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789') for i in range(10))
    User.objects.create(
        username="AnonymousUser",
        password=randomPassword,
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
