# Generated by Django 4.2.11 on 2024-04-16 18:35

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1046_workflowaction_remove_all_correspondents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="dashboard_view_mode",
            field=models.CharField(
                choices=[("table", "Table"), ("small_cards", "Small Cards")],
                default="table",
                max_length=128,
                verbose_name="Dashboard view display mode",
            ),
        ),
        migrations.AddField(
            model_name="savedview",
            name="dashboard_view_limit",
            field=models.PositiveIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Dashboard view limit",
            ),
        ),
        migrations.AddField(
            model_name="savedview",
            name="dashboard_view_table_columns",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("title", "Title"),
                    ("created", "Created"),
                    ("added", "Added"),
                    ("tag", "Tags"),
                    ("documenttype", "Document Type"),
                    ("correspondent", "Correspondent"),
                    ("storagepath", "Storage Path"),
                ],
                default="created,title,tags,correspondent",
                max_length=128,
            ),
        ),
    ]
