# Generated by Django 4.2.11 on 2024-05-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1047_warehouse_document_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='parent_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subwarehouses', to='documents.warehouse'),
        ),
    ]
