# Generated by Django 4.2.11 on 2024-04-23 07:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1048_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
