# Generated by Django <current Django version> on YYYY-MM-DD HH:MM

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1048_previous_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagepath',
            name='use_jinja',
            field=models.BooleanField(default=False, verbose_name='use jinja'),
        ),
    ]
