# Generated by Django 4.2.13 on 2024-07-04 01:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1049_document_deleted_at_document_restored_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="Extra data for the custom field, such as select options",
                null=True,
                verbose_name="extra data",
            ),
        ),
        migrations.AddField(
            model_name="customfieldinstance",
            name="value_select",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("url", "URL"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                    ("monetary", "Monetary"),
                    ("documentlink", "Document Link"),
                    ("select", "Select"),
                ],
                editable=False,
                max_length=50,
                verbose_name="data type",
            ),
        ),
    ]
