# Generated by Django 4.2.11 on 2024-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1050_alter_warehouse_parent_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('name',), 'verbose_name': 'warehouse', 'verbose_name_plural': 'warehouses'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_insensitive',
            field=models.BooleanField(default=True, verbose_name='is insensitive'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='match',
            field=models.CharField(blank=True, max_length=256, verbose_name='match'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='matching_algorithm',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Exact match'), (4, 'Regular expression'), (5, 'Fuzzy word'), (6, 'Automatic')], default=1, verbose_name='matching algorithm'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='documents_warehouse_unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='documents_warehouse_name_uniq'),
        ),
    ]
