# Generated by Django 4.2.15 on 2024-08-20 02:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1051_alter_correspondent_owner_alter_document_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
