# Generated by Django 4.2.11 on 2024-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1051_alter_warehouse_options_warehouse_is_insensitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='path'),
        ),
    ]
