# Generated by Django 4.2.11 on 2024-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1051_alter_warehouse_options_warehouse_is_insensitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtrigger',
            name='filter_has_group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group', verbose_name='has these groups'),
        ),
    ]
