# Generated by Django 4.2.11 on 2024-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1052_warehouse_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='warehouses',
        ),
        migrations.AddField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.warehouse', verbose_name='warehouse'),
        ),
    ]
