# Generated by Django 4.2.11 on 2024-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1053_rename_filter_has_group_workflowtrigger_filter_has_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='has these groups'),
        ),
    ]
