# Generated by Django 4.2.11 on 2024-06-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1054_folder_document_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='checksum',
            field=models.CharField(editable=False, help_text='The checksum of the original folder.', max_length=32, null=True, unique=True, verbose_name='checksum'),
        ),
    ]
