# Generated by Django 4.2.11 on 2024-05-31 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1054_alter_workflowtrigger_filter_has_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('rejected', 'Rejected')], editable=False, max_length=50, verbose_name='status')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('owner', 'Owner')], editable=False, max_length=50, verbose_name='access_type')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('ctype', models.ManyToManyField(blank=True, to='contenttypes.contenttype', verbose_name='ctype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('submitted_by_group', models.ManyToManyField(blank=True, to='auth.group', verbose_name='submitted_by_group')),
            ],
        ),
    ]
