# Generated by Django 5.1.1 on 2024-10-23 20:54

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1055_alter_storagepath_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="schedule_delay",
            field=models.CharField(
                blank=True,
                help_text="The delay before the scheduled trigger is activated.",
                max_length=256,
                null=True,
                verbose_name="schedule delay",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="schedule_delay_custom_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.customfield",
                verbose_name="schedule delay custom field",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="schedule_delay_field",
            field=models.CharField(
                choices=[
                    ("added", "Added"),
                    ("created", "Created"),
                    ("modified", "Modified"),
                    ("custom_field", "Custom Field"),
                ],
                default="added",
                help_text="The field to use for the delay.",
                max_length=20,
                verbose_name="schedule delay field",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtrigger",
            name="type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Consumption Started"),
                    (2, "Document Added"),
                    (3, "Document Updated"),
                    (4, "Scheduled"),
                ],
                default=1,
                verbose_name="Workflow Trigger Type",
            ),
        ),
    ]
