# Generated by Django 5.1.1 on 2024-10-26 16:14

from django.db import migrations

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1055_alter_storagepath_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="transaction_id",
            field=documents.models.Char32UUIDField(blank=True, null=True),
        ),
    ]
