# Generated by Django 4.2.11 on 2024-06-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1055_folder_checksum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='documents_folder_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='documents_folder_name_uniq',
        ),
    ]
