# Generated by Django 4.2.11 on 2024-05-31 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1055_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='submitted_by'),
        ),
    ]
