# Generated by Django 5.1.2 on 2024-10-26 19:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1056_customfieldinstance_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="notification_body",
            field=models.TextField(
                blank=True,
                help_text="The body (message) of the notification, can include some placeholders, see documentation.",
                null=True,
                verbose_name="notification body",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="notification_destination_emails",
            field=models.TextField(
                blank=True,
                help_text="The destination email addresses for the notification, comma separated.",
                null=True,
                verbose_name="notification destination emails",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="notification_destination_url",
            field=models.URLField(
                blank=True,
                help_text="The destination URL for the notification.",
                null=True,
                verbose_name="notification destination url",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="notification_destination_url_headers",
            field=models.JSONField(
                blank=True,
                help_text="The headers to send with the notification destination URL.",
                null=True,
                verbose_name="notification destination url headers",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="notification_include_document",
            field=models.BooleanField(
                default=False,
                verbose_name="include document in notification",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="notification_subject",
            field=models.CharField(
                blank=True,
                help_text="The subject of the notification, can include some placeholders, see documentation.",
                max_length=256,
                null=True,
                verbose_name="notification subject",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="type",
            field=models.PositiveIntegerField(
                choices=[(1, "Assignment"), (2, "Removal"), (3, "Notification")],
                default=1,
                verbose_name="Workflow Action Type",
            ),
        ),
    ]
