# Generated by Django 4.2.11 on 2024-06-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1056_remove_folder_documents_folder_unique_name_owner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='documents_warehouse_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='documents_warehouse_name_uniq',
        ),
    ]
