# Generated by Django 4.2.11 on 2024-06-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '1057_alter_approval_access_type_alter_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='ctype',
            field=models.ManyToManyField(blank=True, null=True, to='contenttypes.contenttype', verbose_name='ctype'),
        ),
    ]
