# Generated by Django 4.2.11 on 2024-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '1058_alter_approval_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtrigger',
            name='filter_has_content_type',
            field=models.ManyToManyField(blank=True, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='workflowtrigger',
            name='filter_has_status',
            field=models.CharField(blank=True, choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], max_length=30, null=True, verbose_name='approval State'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='ctype',
            field=models.ManyToManyField(blank=True, to='contenttypes.contenttype', verbose_name='ctype'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', help_text='Current state of the task being run', max_length=30, verbose_name='Approval State'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Consumption Started'), (2, 'Document Added'), (3, 'Document Updated'), (4, 'Approval Added'), (5, 'Approval Updated')], default=1, verbose_name='Workflow Trigger Type'),
        ),
    ]
