# Generated by Django 5.1.4 on 2025-01-18 19:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1060_alter_customfieldinstance_value_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowactionwebhook",
            name="as_json",
            field=models.BooleanField(default=False, verbose_name="send as JSON"),
        ),
    ]
