# Generated by Django 4.2.11 on 2024-06-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1061_workflowtrigger_filter_has_access_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowtrigger',
            old_name='filter_has_access_type',
            new_name='filter_has_access_types',
        ),
    ]
