# Generated by Django 5.1.6 on 2025-02-16 16:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1062_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowactionwebhook",
            name="url",
            field=models.CharField(
                help_text="The destination URL for the notification.",
                max_length=256,
                verbose_name="webhook url",
            ),
        ),
    ]
