# Generated by Django 5.1.6 on 2025-02-14 01:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1062_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperlesstask",
            name="type",
            field=models.CharField(
                choices=[
                    ("file", "File Task"),
                    ("scheduled_task", "Scheduled Task"),
                    ("manual_task", "Manual Task"),
                ],
                default="file",
                help_text="The type of task that was run",
                max_length=30,
                verbose_name="Task Type",
            ),
        ),
    ]
