# Generated by Django 4.2.11 on 2024-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1062_rename_filter_has_access_type_workflowtrigger_filter_has_access_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_access_types',
            field=models.CharField(blank=True, choices=[('EDIT', 'Edit'), ('VIEW', 'View'), ('OWNER', 'Owner')], max_length=30, null=True, verbose_name='access type'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_status',
            field=models.CharField(blank=True, choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], max_length=30, null=True, verbose_name='approval state'),
        ),
    ]
