# Generated by Django 5.1.6 on 2025-02-28 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1063_paperlesstask_type_alter_paperlesstask_task_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
