# Generated by Django 4.2.11 on 2024-06-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '1063_alter_workflowtrigger_filter_has_access_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtrigger',
            name='filter_has_content_type',
        ),
        migrations.AddField(
            model_name='workflowtrigger',
            name='filter_has_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
