# Generated by Django 5.1.6 on 2025-02-26 17:08

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1063_alter_workflowactionwebhook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="head_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.document",
                verbose_name="head version of document",
            ),
        ),
    ]
