# Generated by Django 5.1.6 on 2025-03-01 18:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1064_delete_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="assign_custom_fields_values",
            field=models.JSONField(
                blank=True,
                help_text="Optional values to assign to the custom fields.",
                null=True,
                verbose_name="custom field values",
                default=dict,
            ),
        ),
    ]
