# Generated by Django 4.2.11 on 2024-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1064_remove_workflowtrigger_filter_has_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtrigger',
            name='filter_has_access_types',
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_content_type',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], max_length=30, null=True, verbose_name='access type'),
        ),
    ]
