# Generated by Django 5.1.6 on 2025-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1065_workflowaction_assign_custom_fields_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_index_ids',
            field=models.JSONField(default=list, help_text='The ids of the embeddings in the vector store.', verbose_name='embedding index ids'),
        ),
    ]
