# Generated by Django 5.1.7 on 2025-04-04 01:08


import django
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1065_workflowaction_assign_custom_fields_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="created",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
        ),
    ]
