# Generated by Django 5.1.7 on 2025-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1066_document_embedding_index_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_image_paths',
            field=models.JSONField(default=list, help_text='The paths of the images extracted during OCR processing.', verbose_name='OCR image paths'),
        ),
    ]
