# Generated by Django 4.2.11 on 2024-06-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1066_workflowaction_assign_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowtrigger',
            old_name='filter_has_access_types',
            new_name='filter_has_access_type',
        ),
    ]
