# Generated by Django 4.2.11 on 2024-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1067_rename_filter_has_access_types_workflowtrigger_filter_has_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='object_pk',
            field=models.CharField(blank=True, max_length=255, verbose_name='object ID'),
        ),
    ]
