# Generated by Django 5.1.7 on 2025-04-04 20:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1067_document_ocr_image_paths"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="ocr_image_paths",
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_image_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of images extracted during OCR processing.",
                verbose_name="number of OCR images",
            ),
        ),
    ]
