# Generated by Django 5.2.5 on 2025-09-02 09:45

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_storage_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.storagepath",
                verbose_name="has this storage path",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_custom_fields",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflow_triggers_filter_custom_fields",
                to="documents.customfield",
                verbose_name="has these custom fields",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_custom_fields_values",
            field=models.JSONField(
                blank=True,
                null=True,
                default=dict,
                verbose_name="custom field values",
                help_text="Values of the custom fields that must match.",
            ),
        ),
    ]
