# Generated by Django 5.2.6 on 2025-09-11 17:29

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_storage_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.storagepath",
                verbose_name="has this storage path",
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="assign_title",
            field=models.TextField(
                blank=True,
                help_text="Assign a document title, must  be a Jinja2 template, see documentation.",
                null=True,
                verbose_name="assign title",
            ),
        ),
    ]
