# Generated by Django 5.2.5 on 2025-08-26 07:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1068_alter_document_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="in_process",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the document is currently being processed.",
                verbose_name="in process",
            ),
        ),
    ]
