# Generated by Django 5.2.6 on 2025-09-13 17:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1069_workflowtrigger_filter_has_storage_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfieldinstance",
            name="value_long_text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("longstring", "Long String"),
                    ("string", "String"),
                    ("url", "URL"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                    ("monetary", "Monetary"),
                    ("documentlink", "Document Link"),
                    ("select", "Select"),
                ],
                editable=False,
                max_length=50,
                verbose_name="data type",
            ),
        ),
    ]
