# Generated by Django 5.2.5 on 2025-09-02 09:45

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1069_migrate_workflow_title_jinja"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_storage_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.storagepath",
                verbose_name="has this storage path",
            ),
        ),
    ]
