# Generated by Django 5.1.5 on 2025-02-10 06:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1069_workflowtrigger_filter_has_storage_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.tag",
                verbose_name="parent",
            ),
        ),
    ]
