# Generated by Django 4.2.11 on 2024-06-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1069_remove_approval_ctype_approval_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='access_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], editable=False, max_length=50, verbose_name='access_type'),
        ),
    ]
