# Generated by Django 4.2.11 on 2024-06-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1070_alter_approval_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='access_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], max_length=30, null=True, verbose_name='access type'),
        ),
    ]
