# Generated by Django 5.2.6 on 2025-10-07 18:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1071_tag_tn_ancestors_count_tag_tn_ancestors_pks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_custom_field_query",
            field=models.TextField(
                blank=True,
                help_text="JSON-encoded custom field query expression.",
                null=True,
                verbose_name="filter custom field query",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_all_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_all",
                to="documents.tag",
                verbose_name="has all of these tag(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_correspondents",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not_correspondent",
                to="documents.correspondent",
                verbose_name="does not have these correspondent(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_document_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not_document_type",
                to="documents.documenttype",
                verbose_name="does not have these document type(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_storage_paths",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not_storage_path",
                to="documents.storagepath",
                verbose_name="does not have these storage path(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not",
                to="documents.tag",
                verbose_name="does not have these tag(s)",
            ),
        ),
    ]
