# Generated by Django 5.2.6 on 2025-10-07 16:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1071_tag_tn_ancestors_count_tag_tn_ancestors_pks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_all_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_all",
                to="documents.tag",
                verbose_name="has all of these tag(s)",
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_not_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="workflowtriggers_has_not",
                to="documents.tag",
                verbose_name="does not have these tag(s)",
            ),
        ),
    ]
