# Generated by Django 5.1.8 on 2025-04-30 02:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1072_workflowtrigger_filter_custom_field_query_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperlesstask",
            name="task_name",
            field=models.CharField(
                choices=[
                    ("consume_file", "Consume File"),
                    ("train_classifier", "Train Classifier"),
                    ("check_sanity", "Check Sanity"),
                    ("index_optimize", "Index Optimize"),
                    ("llmindex_update", "LLM Index Update"),
                ],
                help_text="Name of the task that was run",
                max_length=255,
                null=True,
                verbose_name="Task Name",
            ),
        ),
    ]
