# Generated by Django 4.2.11 on 2024-06-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1073_alter_approval_submitted_by_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='access_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], default=1, max_length=30, verbose_name='access type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='submitted_by_group',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='submitted_by_group'),
        ),
    ]
