# Generated by Django 5.2.6 on 2025-10-27 15:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1073_migrate_workflow_title_jinja"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
