# Generated by Django 5.2.6 on 2025-12-10 10:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1074_workflowrun_deleted_at_workflowrun_restored_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_length",
            field=models.PositiveIntegerField(
                null=True,
                default=None,
                editable=False,
                help_text="The length of the content field in characters. Automatically set when the document is saved. Used to compute statistics faster.",
                verbose_name="content length",
            ),
        ),
    ]
