# Generated by Django 5.2.6 on 2025-12-10 10:40

from django.db import migrations
from django.db import models


def populate_content_length(apps, schema_editor):
    """
    Populate content_length for existing documents using raw SQL.
    - PostgreSQL/MariaDB: CHAR_LENGTH() counts characters (not bytes)
    - SQLite: LENGTH() already counts characters for TEXT columns
    """
    from django.db import connection

    vendor = connection.vendor
    if vendor == "sqlite":
        sql = "UPDATE documents_document SET content_length = LENGTH(content)"
    else:
        # PostgreSQL and MariaDB/MySQL
        sql = "UPDATE documents_document SET content_length = CHAR_LENGTH(content)"

    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1074_workflowrun_deleted_at_workflowrun_restored_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_length",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="The length of the content field in characters. Automatically set when the document is saved. Used to compute statistics faster.",
                verbose_name="content length",
            ),
        ),
        migrations.RunPython(
            populate_content_length,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
