# Generated by Django 5.2.6 on 2025-12-10 10:40

from django.db import connection
from django.db import migrations
from django.db import models

# Threshold above which we skip backfilling in the migration
# to avoid long-running migrations on large databases
BACKFILL_THRESHOLD = 1000


def backfill_content_length(apps, schema_editor):
    """
    Backfill content_length for existing documents if the table is small enough.
    For large tables, users should run the management command instead.
    """
    Document = apps.get_model("documents", "Document")
    count = Document.objects.count()

    if count == 0:
        return

    if count > BACKFILL_THRESHOLD:
        # Will be handled by a warning at app startup + management command
        return

    # Use the appropriate function for the database backend
    vendor = connection.vendor
    if vendor == "sqlite":
        length_func = "LENGTH"
    else:
        # PostgreSQL and MariaDB/MySQL use CHAR_LENGTH
        length_func = "CHAR_LENGTH"

    with connection.cursor() as cursor:
        cursor.execute(
            f'UPDATE documents_document SET content_length = {length_func}("content")',
        )


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1074_workflowrun_deleted_at_workflowrun_restored_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_length",
            field=models.PositiveIntegerField(
                null=True,
                default=None,
                editable=False,
                help_text="The length of the content field in characters. Automatically set when the document is saved. Used to compute statistics faster.",
                verbose_name="content length",
            ),
        ),
        migrations.RunPython(
            backfill_content_length,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
