# Generated by Django 5.2.7 on 2026-01-14 16:53

from django.db import migrations
from django.db import models


def populate_action_order(apps, schema_editor):
    WorkflowAction = apps.get_model("documents", "WorkflowAction")
    for index, action in enumerate(WorkflowAction.objects.all()):
        action.order = index
        action.save()


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1075_alter_paperlesstask_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="order"),
        ),
        migrations.RunPython(
            populate_action_order,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
