# Generated by Django 4.2.11 on 2024-06-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1075_alter_approval_submitted_by_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='access_type',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], max_length=30, verbose_name='access type'),
        ),
    ]
