# Generated by Django 5.2.7 on 2026-01-14 17:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1076_alter_paperlesstask_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                editable=False,
                max_length=32,
                verbose_name="checksum",
                help_text="The checksum of the original document.",
            ),
        ),
    ]
