# Generated by Django 5.2.9 on 2026-01-21 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1076_alter_paperlesstask_task_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="storage_type",
        ),
    ]
