# Generated by Django 4.2.11 on 2024-06-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1053_remove_document_warehouses_document_warehouse'),
        ('documents', '1077_alter_approval_submitted_by_group'),
    ]

    operations = [
    ]
