# Generated by Django 4.2.11 on 2024-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1078_merge_20240604_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='expiration',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expiration'),
        ),
    ]
