# Generated by Django 4.2.11 on 2024-06-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1055_folder_checksum'),
        ('documents', '1079_approval_expiration'),
    ]

    operations = [
    ]
