# Generated by Django 4.2.11 on 2024-06-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1057_remove_warehouse_documents_warehouse_unique_name_owner_and_more'),
        ('documents', '1080_merge_1055_folder_checksum_1079_approval_expiration'),
    ]

    operations = [
    ]
