# Generated by Django 4.2.11 on 2024-07-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1081_merge_20240627_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='folder', editable=False, max_length=50, verbose_name='type'),
        ),
    ]
