# Generated by Django 4.2.11 on 2024-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1082_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(blank=True, choices=[('folder', 'folder'), ('file', 'file')], default='folder', max_length=20, null=True),
        ),
    ]
