# Generated by Django 4.2.11 on 2024-07-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1084_alter_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldinstance',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
