# Generated by Django 4.2.11 on 2024-07-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1084_alter_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldinstance',
            name='match',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('match', models.CharField(blank=True, max_length=256, verbose_name='match')),
                ('matching_algorithm', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Exact match'), (4, 'Regular expression'), (5, 'Fuzzy word'), (6, 'Automatic')], default=1, verbose_name='matching algorithm')),
                ('is_insensitive', models.BooleanField(default=True, verbose_name='is insensitive')),
                ('dossier_type', models.CharField(choices=[('DOSSIER', 'Dossier'), ('DOCUMENT', 'Document')], default='DOSSIER', max_length=30, verbose_name='access_type')),
                ('key', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=128, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('is_form', models.BooleanField(default=False, verbose_name='is form')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('parent_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.dossier')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfieldinstance',
            name='dossier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.dossier'),
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.dossier', verbose_name='dossier'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='documents_dossier_unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='documents_dossier_name_uniq'),
        ),
    ]
