# Generated by Django 4.2.11 on 2024-07-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1085_customfieldinstance_match_dossier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='code',
        ),
    ]
