# Generated by Django 4.2.11 on 2024-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1086_remove_dossier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='path'),
        ),
    ]
