# Generated by Django 4.2.11 on 2024-07-04 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1086_remove_folder_created_remove_folder_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='folder',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='updated'),
        ),
    ]
