# Generated by Django 4.2.11 on 2024-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1087_dossier_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='url'),
        ),
    ]
