# Generated by Django 4.2.11 on 2024-07-04 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1087_folder_created_folder_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='updated'),
        ),
    ]
