# Generated by Django 4.2.11 on 2024-07-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1088_dossier_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldinstance',
            name='document',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='documents.document'),
        ),
    ]
