# Generated by Django 4.2.11 on 2024-07-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1086_alter_customfieldinstance_value_text'),
        ('documents', '1088_alter_folder_created_alter_folder_updated'),
    ]

    operations = [
    ]
