# Generated by Django 4.2.11 on 2024-07-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1089_alter_customfieldinstance_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldinstance',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.customfieldinstance'),
        ),
    ]
