# Generated by Django 4.2.11 on 2024-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1090_customfieldinstance_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldinstance',
            name='match',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
