# Generated by Django 4.2.11 on 2024-07-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1091_alter_customfieldinstance_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfieldinstance',
            old_name='match',
            new_name='match_value',
        ),
    ]
