# Generated by Django 4.2.11 on 2024-07-16 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1092_rename_match_customfieldinstance_match_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldinstance',
            name='dossier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='documents.dossier'),
        ),
    ]
