# Generated by Django 4.2.11 on 2024-07-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1093_alter_customfieldinstance_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='parent_dossier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dossier_types', to='documents.dossier'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='parent_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dossiers', to='documents.dossier'),
        ),
    ]
