# Generated by Django 4.2.11 on 2024-07-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1094_dossier_parent_dossier_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='dossier_type',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='is_form',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='key',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='parent_dossier_type',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='url',
        ),
        migrations.AddField(
            model_name='dossier',
            name='type',
            field=models.CharField(choices=[('DOSSIER', 'Dossier'), ('DOCUMENT', 'Document'), ('FILE', 'File')], default='DOSSIER', max_length=30, verbose_name='access_type'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='parent_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.dossier'),
        ),
        migrations.CreateModel(
            name='DossierForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('match', models.CharField(blank=True, max_length=256, verbose_name='match')),
                ('matching_algorithm', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Exact match'), (4, 'Regular expression'), (5, 'Fuzzy word'), (6, 'Automatic')], default=1, verbose_name='matching algorithm')),
                ('is_insensitive', models.BooleanField(default=True, verbose_name='is insensitive')),
                ('type', models.CharField(choices=[('DOSSIER', 'Dossier'), ('DOCUMENT', 'Document')], default='DOSSIER', max_length=30, verbose_name='access_type')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('key', models.CharField(max_length=128, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'dossier type',
                'verbose_name_plural': 'dossiers type',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfieldinstance',
            name='dossier_form',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='documents.dossierform'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dossier_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.dossierform'),
        ),
        migrations.AddConstraint(
            model_name='dossierform',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='documents_dossierform_unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='dossierform',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='documents_dossierform_name_uniq'),
        ),
    ]
