# Generated by Django 4.2.11 on 2024-07-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1095_remove_dossier_dossier_type_remove_dossier_is_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dossier_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.dossierform', verbose_name='dossier forms'),
        ),
    ]
