# Generated by Django 4.2.11 on 2024-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1096_document_dossier_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierform',
            name='form_rule',
            field=models.TextField(blank=True, null=True, verbose_name='form_rule'),
        ),
        migrations.AlterField(
            model_name='dossierform',
            name='key',
            field=models.TextField(blank=True, null=True, verbose_name='key'),
        ),
    ]
