# Generated by Django 4.2.11 on 2024-07-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1097_dossierform_form_rule_alter_dossierform_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierform',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='dossierform',
            name='username',
            field=models.TextField(blank=True, null=True, verbose_name='username'),
        ),
    ]
