# Generated by Django 4.2.11 on 2024-07-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1098_dossierform_password_dossierform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierform',
            name='url_login',
            field=models.TextField(blank=True, null=True, verbose_name='url_login'),
        ),
    ]
