# Generated by Django 5.2.9 on 2026-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1086_make_note_tenant_id_non_nullable'),
        ('documents', '1090_add_rls_policy_for_sharelink'),
        ('documents', '1098_add_rls_policy_for_workflow_models'),
    ]

    operations = [
    ]
