# Generated by Django 4.2.11 on 2024-07-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1099_dossierform_url_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierform',
            name='url_refresh',
            field=models.TextField(blank=True, null=True, verbose_name='url_refresh'),
        ),
    ]
