# Generated by Django 4.2.11 on 2024-08-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1102_alter_customfieldinstance_value_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierform',
            options={'ordering': ('name',), 'verbose_name': 'dossier form', 'verbose_name_plural': 'dossiers form'},
        ),
        migrations.RemoveField(
            model_name='dossierform',
            name='key',
        ),
        migrations.RemoveField(
            model_name='dossierform',
            name='url',
        ),
    ]
