# Generated by Django 4.2.11 on 2024-08-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1103_alter_dossierform_options_remove_dossierform_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dossierform',
            name='username',
        ),
    ]
