# Generated by Django 4.2.11 on 2024-08-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1089_merge_20240712_0342'),
        ('documents', '1104_remove_dossierform_password_and_more'),
    ]

    operations = [
    ]
