# Generated by Django 4.2.11 on 2024-11-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1105_merge_20240806_0218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dossier',
            name='documents_dossier_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='dossier',
            name='documents_dossier_name_uniq',
        ),
    ]
