# Generated by Django 4.2.11 on 2024-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1106_remove_dossier_documents_dossier_unique_name_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_access_type',
            field=models.CharField(blank=True, choices=[('OWNER', 'OWNER'), ('EDIT', 'EDIT'), ('VIEW', 'VIEW')], max_length=30, null=True, verbose_name='access type'),
        ),
    ]
