# Generated by Django 4.2.11 on 2024-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1107_alter_workflowtrigger_filter_has_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtrigger',
            name='filter_has_access_type',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], max_length=30, null=True, verbose_name='access type'),
        ),
    ]
