# Generated by Django 4.2.11 on 2024-12-11 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1108_alter_workflowtrigger_filter_has_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(help_text='The number of pages of the document.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='page count'),
        ),
    ]
