# Generated by Django 4.2.11 on 2024-12-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1110_fontlanguage_archivefont_document_archive_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='font_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.fontlanguage', verbose_name='font languages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='archive_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.archivefont', verbose_name='archive fonts'),
        ),
    ]
