# Generated by Django 4.2.11 on 2024-12-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1111_document_font_language_alter_document_archive_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
