# Generated by Django 4.2.11 on 2024-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1112_document_deleted_at_document_restored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
