# Generated by Django 4.2.11 on 2024-12-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1113_dossier_deleted_at_dossier_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='documents.dossier', verbose_name='dossier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='documents.folder', verbose_name='folder'),
        ),
    ]
