# Generated by Django 4.2.11 on 2025-01-03 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1114_alter_document_dossier_alter_document_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restore_at', models.DateTimeField(db_index=True,
                                                    default=django.utils.timezone.now,
                                                    editable=False, null=True,
                                                    verbose_name='restored_at')),
                ('restore_status', models.FloatField(blank=True, default=0)),
                ('backup_status', models.FloatField(blank=True, default=0)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            to=settings.AUTH_USER_MODEL,
                                            verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
