# Generated by Django 4.2.11 on 2025-01-09 03:57

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1115_backuprecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="parent_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="documents.folder",
            ),
        ),
    ]
