# Generated by Django 4.2.11 on 2025-01-10 04:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1116_alter_folder_parent_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuprecord",
            name="restore_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="restored_at",
            ),
        ),
    ]
