# Generated by Django 4.2.11 on 2025-01-10 10:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1117_alter_backuprecord_restore_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuprecord",
            name="restore_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="restored_at",
            ),
        ),
    ]
