# Generated by Django 4.2.11 on 2025-01-11 03:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1118_alter_backuprecord_restore_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="is_backup",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="is_restore",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
