# Generated by Django 4.2.11 on 2025-01-12 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1119_backuprecord_is_backup_backuprecord_is_restore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuprecord",
            name="count",
        ),
    ]
