# Generated by Django 4.2.11 on 2025-02-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1120_remove_backuprecord_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlesstask',
            name='api_call_count',
            field=models.IntegerField(default=0, help_text='API call count', null=True, verbose_name='API call count'),
        ),
    ]
