# Generated by Django 4.2.11 on 2025-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1121_edoctask_api_call_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='file_id'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, related_name='document_types', to='documents.customfield', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='map_key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='map_key'),
        ),
    ]
