# Generated by Django 4.2.11 on 2025-03-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1122_document_file_id_documenttype_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='map_key',
        ),
        migrations.AddField(
            model_name='customfield',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='code'),
        ),
    ]
