# Generated by Django 4.2.11 on 2025-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1123_remove_documenttype_map_key_customfield_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
