# Generated by Django 4.2.11 on 2025-03-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1124_document_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='document_types', to='documents.customfield', verbose_name='tags'),
        ),
    ]
