# Generated by Django 4.2.11 on 2025-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1125_alter_documenttype_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, related_name='document_types', to='documents.customfield', verbose_name='custom_fields'),
        ),
    ]
