# Generated by Django 4.2.11 on 2025-04-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1126_alter_documenttype_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True, verbose_name='file_id'),
        ),
    ]
