# Generated by Django 4.2.11 on 2025-04-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents',
         '1129_alter_archivefont_name_alter_correspondent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edoctask',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'OCR_RETRY'),
                                                           (2, 'OCR_WEBHOOK')],
                                      db_index=True,
                                      help_text='Select the type of OCR task to execute.',
                                      null=True),
        ),
    ]
