# Generated by Django 4.2.11 on 2025-05-20 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1130_edoctask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='archive_filename',
            field=models.FilePathField(default=None, editable=False,
                                       help_text='Current archive filename in storage',
                                       max_length=1024, null=True, unique=True,
                                       verbose_name='archive filename'),
        ),
        migrations.AddField(
            model_name='folder',
            name='documents_count',
            field=models.PositiveIntegerField(blank=True, default=0,
                                              help_text='Number of documents in the folder',
                                              null=True,
                                              verbose_name='documents count'),
        ),
        migrations.AddField(
            model_name='folder',
            name='filename',
            field=models.FilePathField(default=None, editable=False,
                                       help_text='Current filename in storage',
                                       max_length=1024, null=True, unique=True,
                                       verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='folder',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True,
                                       verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='folder',
            name='original_filename',
            field=models.CharField(default=None, editable=False,
                                   help_text='The original name of the file when it was uploaded',
                                   max_length=1024, null=True,
                                   verbose_name='original filename'),
        ),
        migrations.AddField(
            model_name='folder',
            name='page_count',
            field=models.PositiveIntegerField(
                help_text='The number of pages of the document.', null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='page count'),
        ),
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.BigIntegerField(blank=True, default=0,
                                         help_text='Size of the folder in bytes',
                                         null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='archivefont',
            name='note',
            field=models.TextField(blank=True,
                                   help_text='Note for the archive font',
                                   null=True, verbose_name='note'),
        ),
    ]
