# Generated by Django 4.2.11 on 2025-05-20 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents',
         '1131_folder_archive_filename_folder_documents_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='document_count',
            field=models.PositiveIntegerField(
                help_text='The number of document of the folder.', null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='document count'),
        ),
    ]
