# Generated by Django 4.2.11 on 2025-05-20 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1132_folder_document_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='size',
            new_name='filesize',
        ),
    ]
