# Generated by Django 4.2.11 on 2025-05-21 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1133_rename_size_folder_filesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='page_count',
        ),
        migrations.AlterField(
            model_name='folder',
            name='document_count',
            field=models.PositiveIntegerField(default=0,
                                              help_text='The number of document of the folder.',
                                              null=True, validators=[
                    django.core.validators.MinValueValidator(1)],
                                              verbose_name='document count'),
        ),
    ]
