# Generated by Django 4.2.11 on 2025-05-23 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('documents',
         '1134_remove_folder_page_count_alter_folder_document_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='documents_count',
        ),
    ]
