# Generated by Django 4.2.11 on 2025-05-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1135_remove_folder_documents_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='checksum',
            field=models.CharField(editable=False,
                                   help_text='The checksum of the original document.',
                                   max_length=32, verbose_name='checksum'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='checksum',
            field=models.CharField(editable=False,
                                   help_text='The checksum of the original folder.',
                                   max_length=32, null=True,
                                   verbose_name='checksum'),
        ),
    ]
