# Generated by Django 4.2.11 on 2025-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1136_alter_document_checksum_alter_folder_checksum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='checksum',
        ),
        migrations.AddField(
            model_name='folder',
            name='name_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='path'),
        ),
    ]
