# Generated by Django 4.2.11 on 2025-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'documents', '1137_remove_folder_checksum_folder_name_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edoctask',
            name='id_reference',
            field=models.BigIntegerField(blank=True, null=True,
                                         verbose_name='ID Reference'),
        ),
    ]
