# Generated by Django 4.2.11 on 2025-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1138_edoctask_id_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='main_pos',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='main_pos'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='map'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='status'),
        ),
    ]
