# Generated by Django 4.2.11 on 2025-06-17 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1138_edoctask_id_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The path of the folder.',
                                          max_length=512,
                                          verbose_name='Path')),
                ('can_not_edit_groups', models.ManyToManyField(blank=True,
                                                               help_text='Groups that are restricted from editing the folder.',
                                                               related_name='restricted_edit_folders',
                                                               to='auth.group',
                                                               verbose_name='Restricted Edit Groups')),
                ('can_not_edit_users', models.ManyToManyField(blank=True,
                                                              help_text='Users who are restricted from editing the folder.',
                                                              related_name='restricted_edit_folders',
                                                              to=settings.AUTH_USER_MODEL,
                                                              verbose_name='Restricted Edit Users')),
                ('can_not_view_groups', models.ManyToManyField(blank=True,
                                                               help_text='Groups that are restricted from viewing the folder.',
                                                               related_name='restricted_view_folders',
                                                               to='auth.group',
                                                               verbose_name='Restricted View Groups')),
                ('can_not_view_users', models.ManyToManyField(blank=True,
                                                              help_text='Users who are restricted from viewing the folder.',
                                                              related_name='restricted_view_folders',
                                                              to=settings.AUTH_USER_MODEL,
                                                              verbose_name='Restricted View Users')),
                ('edit_groups', models.ManyToManyField(blank=True,
                                                       help_text='Groups that have edit permissions for the folder.',
                                                       related_name='editable_folders',
                                                       to='auth.group',
                                                       verbose_name='Edit Groups')),
                ('edit_users', models.ManyToManyField(blank=True,
                                                      help_text='Users who have edit permissions for the folder.',
                                                      related_name='editable_folders',
                                                      to=settings.AUTH_USER_MODEL,
                                                      verbose_name='Edit Users')),
                ('owner', models.ForeignKey(blank=True,
                                            help_text='The owner of the folder.',
                                            null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='owned_folders',
                                            to=settings.AUTH_USER_MODEL,
                                            verbose_name='Owner')),
                ('view_groups', models.ManyToManyField(blank=True,
                                                       help_text='Groups that have view permissions for the folder.',
                                                       related_name='viewable_folders',
                                                       to='auth.group',
                                                       verbose_name='View Groups')),
                ('view_users', models.ManyToManyField(blank=True,
                                                      help_text='Users who have view permissions for the folder.',
                                                      related_name='viewable_folders',
                                                      to=settings.AUTH_USER_MODEL,
                                                      verbose_name='View Users')),
            ],
            options={
                'verbose_name': 'Folder Permission',
                'verbose_name_plural': 'Folder Permissions',
            },
        ),
    ]
