# Generated by Django 4.2.11 on 2025-06-19 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '1139_folderpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderpermission',
            name='owner',
        ),
    ]
