# Generated by Django 4.2.11 on 2025-06-21 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1140_remove_folderpermission_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='delete',
            field=models.BooleanField(default=False,
                                      verbose_name='Can Delete'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='download',
            field=models.BooleanField(default=False,
                                      verbose_name='Can Download'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='edit',
            field=models.BooleanField(default=False, verbose_name='Can Edit'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='folder_permissions',
                                    to='auth.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='folder_permissions',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='User'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='view',
            field=models.BooleanField(default=False, verbose_name='Can View'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('user', 'group', 'path')},
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='can_not_edit_groups',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='can_not_edit_users',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='can_not_view_groups',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='can_not_view_users',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='edit_groups',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='edit_users',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='view_groups',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='view_users',
        ),
    ]
