# Generated by Django 4.2.11 on 2025-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1141_warehouse_manage_by_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_manage_by_company',
            field=models.BooleanField(default=False, verbose_name='is_manage_by_company'),
        ),
    ]
