# Generated by Django 4.2.11 on 2025-06-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1142_warehouse_is_manage_by_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='name')),
                ('match', models.CharField(blank=True, max_length=256, verbose_name='match')),
                ('matching_algorithm', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Any word'), (2, 'All words'), (3, 'Exact match'), (4, 'Regular expression'), (5, 'Fuzzy word'), (6, 'Automatic')], default=1, verbose_name='matching algorithm')),
                ('is_insensitive', models.BooleanField(default=True, verbose_name='is insensitive')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Move Timestamp')),
                ('move_reason', models.TextField(blank=True, null=True, verbose_name='Reason for Move')),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-move_timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='ManageDepartment',
        ),
        migrations.RemoveConstraint(
            model_name='managedepartment',
            name='documents_department_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='managedepartment',
            name='documents_department_name_uniq',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code_in_box',
            field=models.CharField(max_length=256, null=True, verbose_name='code_in_box'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='handover_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='handover_date'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='recived_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='recived_date'),
        ),
        migrations.AddConstraint(
            model_name='managedepartment',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='documents_managedepartment_unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='managedepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='documents_managedepartment_name_uniq'),
        ),
        migrations.AddField(
            model_name='movedhistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_history', to='documents.document', verbose_name='Document moved history'),
        ),
        migrations.AddField(
            model_name='movedhistory',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_history', to=settings.AUTH_USER_MODEL, verbose_name='Moved By'),
        ),
        migrations.AddField(
            model_name='movedhistory',
            name='new_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_location_histories', to='documents.warehouse', verbose_name='New Location'),
        ),
        migrations.AddField(
            model_name='movedhistory',
            name='old_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_location_history', to='documents.warehouse', verbose_name='Old location'),
        ),
        migrations.AddField(
            model_name='createddepartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddConstraint(
            model_name='createddepartment',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='documents_createddepartment_unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='createddepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='documents_createddepartment_name_uniq'),
        ),
    ]
