# Generated by Django 4.2.11 on 2025-06-18 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1143_createddepartment_movedhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerMoveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Move Timestamp')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_moved_history', to='documents.warehouse', verbose_name='Container moved history')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Move By')),
                ('new_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_parent_of', to='documents.warehouse', verbose_name='New parent')),
                ('old_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_parent_of', to='documents.warehouse', verbose_name='Old parent')),
            ],
            options={
                'verbose_name': 'Container Moved History',
                'verbose_name_plural': 'Container Moved Histories',
                'ordering': ['-moved_timestamp'],
            },
        ),
    ]
