# Generated by Django 4.2.11 on 2025-06-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1144_containermovehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containermovehistory',
            options={'ordering': ['-move_timestamp'], 'verbose_name': 'Container Moved History', 'verbose_name_plural': 'Container Moved Histories'},
        ),
        migrations.RenameField(
            model_name='containermovehistory',
            old_name='moved_timestamp',
            new_name='move_timestamp',
        ),
    ]
