# Generated by Django 4.2.11 on 2025-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1145_alter_containermovehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermovehistory',
            name='move_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Move'),
        ),
    ]
