# Generated by Django 4.2.11 on 2025-06-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1146_containermovehistory_move_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='status',
        ),
        migrations.AddField(
            model_name='createddepartment',
            name='location',
            field=models.TextField(blank=True, max_length=102, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='createddepartment',
            name='main_pos',
            field=models.CharField(blank=True, max_length=20, verbose_name='main pos'),
        ),
        migrations.AddField(
            model_name='createddepartment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='boxcase_status',
            field=models.CharField(blank=True, choices=[('wait_for_delivery', 'Wait for Delivery'), ('delivering', 'Delivering'), ('destroyed', 'Delivered'), ('stored', 'Stored'), ('opened', 'Opened'), ('destroyed', 'Destroyed')], db_index=True, default='wait_for_delivery', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='handover_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_to_department', to='documents.createddepartment', verbose_name='handover_to_department'),
        ),
    ]
