# Generated by Django 4.2.11 on 2025-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1147_remove_warehouse_status_createddepartment_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createddepartment',
            name='department_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department Type'),
        ),
    ]
