# Generated by Django 4.2.11 on 2025-06-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1148_createddepartment_department_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='handover_to_department',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_department', to='documents.createddepartment', verbose_name='source_department'),
        ),
    ]
