# Generated by Django 4.2.11 on 2025-06-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1149_remove_warehouse_handover_to_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseMoveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('in_transit', 'In Transit'), ('received', 'Received')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái yêu cầu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ngày tạo yêu cầu')),
                ('external_shipper', models.CharField(blank=True, max_length=255, verbose_name='Tên đơn vị vận chuyển ngoài')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn')),
                ('expected_receive_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhận dự kiến')),
                ('actual_shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi thực tế')),
                ('actual_receive_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày nhận thực tế')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('confirmed_by_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận nhận')),
                ('confirmed_by_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận gửi')),
                ('container_to_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_requests', to='documents.warehouse', verbose_name='Kho nguồn')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.warehouse', verbose_name='Kho đích')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo yêu cầu')),
                ('source_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.warehouse', verbose_name='Vị trí nguồn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
