# Generated by Django 4.2.11 on 2025-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1150_warehousemoverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemoverequest',
            name='reason',
            field=models.TextField(blank=True, verbose_name='reason'),
        ),
    ]
