# Generated by Django 4.2.11 on 2025-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1151_warehousemoverequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='boxcase_status',
            field=models.CharField(blank=True, choices=[('wait_for_delivery', 'Wait for Delivery'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('stored', 'Stored'), ('opened', 'Opened'), ('destroyed', 'Destroyed')], db_index=True, default='wait_for_delivery', max_length=50, null=True, verbose_name='Boxcase Status'),
        ),
    ]
