# Generated by Django 4.2.11 on 2025-06-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1141_folderpermission_delete_folderpermission_download_and_more'),
        ('documents', '1153_alter_warehouse_boxcase_status'),
    ]

    operations = [
    ]
