# Generated by Django 4.2.11 on 2025-06-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1154_merge_20250624_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemoverequest',
            name='external_shipper',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đơn vị vận chuyển ngoài'),
        ),
        migrations.AlterField(
            model_name='warehousemoverequest',
            name='reason',
            field=models.TextField(verbose_name='reason'),
        ),
        migrations.CreateModel(
            name='WarehouseMoveRequesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_on_receipt', models.TextField(blank=True, verbose_name='Mô tả tình trạng lúc nhận')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú chi tiết')),
                ('photo_on_ship', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ảnh khi giao')),
                ('photo_on_receive', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ảnh lúc nhận')),
                ('boxcase', models.ForeignKey(limit_choices_to={'type': 'Boxcase'}, on_delete=django.db.models.deletion.PROTECT, to='documents.warehouse')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.warehouse')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='documents.warehousemoverequest')),
            ],
            options={
                'unique_together': {('request', 'boxcase')},
            },
        ),
    ]
