# Generated by Django 4.2.11 on 2025-06-25 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1155_alter_warehousemoverequest_external_shipper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOpeningReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã báo cáo')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Trạng thái báo cáo')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú kiểm kê')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mở thùng')),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='boxcase_status',
            field=models.CharField(blank=True, choices=[('wait_for_delivery', 'Wait for Delivery'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('stored', 'Stored'), ('opened', 'Opened'), ('destroyed', 'Destroyed')], db_index=True, default='wait_for_delivery', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_checked', 'Chưa kiểm tra'), ('present', 'Có mặt, tình trạng tốt'), ('missing', 'Thất lạc'), ('damaged', 'Hư hỏng')], default='not_checked', max_length=20, verbose_name='Trạng thái kiểm kê')),
                ('is_quantity_confirmed', models.BooleanField(default=False, verbose_name='Xác nhận đủ số lượng')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Mô tả tình trạng')),
                ('condition_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ảnh tình trạng')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.document')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='documents.boxopeningreport')),
            ],
        ),
        migrations.AddField(
            model_name='boxopeningreport',
            name='boxcase',
            field=models.OneToOneField(limit_choices_to={'type': 'Boxcase'}, on_delete=django.db.models.deletion.PROTECT, related_name='opening_report', to='documents.warehouse'),
        ),
        migrations.AddField(
            model_name='boxopeningreport',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm kê'),
        ),
    ]
