# Generated by Django 4.0.4 on 2022-04-12 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edoc_mail", "0009_alter_mailrule_action_alter_mailrule_folder"),
        ("edoc_mail", "0012_alter_mailrule_assign_tags"),
    ]

    operations = []
