# Generated by Django 5.2.5 on 2025-08-21 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '1068_alter_document_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('tesseract_lang', models.CharField(default='fra+eng', max_length=50, verbose_name='Langues Tesseract')),
                ('tesseract_psm', models.IntegerField(default=6, verbose_name='Page Segmentation Mode')),
                ('tesseract_oem', models.IntegerField(default=3, verbose_name='OCR Engine Mode')),
                ('doctr_model', models.CharField(default='db_resnet50', max_length=50, verbose_name='Modèle de détection Doctr')),
                ('doctr_recognition_model', models.CharField(default='crnn_vgg16_bn', max_length=50, verbose_name='Modèle de reconnaissance Doctr')),
                ('max_image_size', models.IntegerField(default=3000, verbose_name='Taille max des images (px)')),
                ('dpi', models.IntegerField(default=300, verbose_name='DPI pour conversion PDF')),
                ('enhance_image', models.BooleanField(default=True, verbose_name='Amélioration automatique')),
                ('denoise', models.BooleanField(default=True, verbose_name='Débruitage')),
                ('max_memory_mb', models.IntegerField(default=1024, verbose_name='Mémoire max (MB)')),
                ('batch_size', models.IntegerField(default=4, verbose_name='Taille des lots')),
                ('is_active', models.BooleanField(default=False, verbose_name='Configuration active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration OCR',
                'verbose_name_plural': 'Configurations OCR',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OCRQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engines', models.JSONField(default=list, help_text='Liste des moteurs OCR à exécuter', verbose_name='Moteurs à exécuter')),
                ('priority', models.IntegerField(choices=[(1, 'Basse'), (5, 'Normale'), (10, 'Haute'), (20, 'Urgente')], default=5, verbose_name='Priorité')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Programmé pour')),
                ('retries', models.IntegerField(default=0, verbose_name='Tentatives')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Tentatives max')),
                ('status', models.CharField(choices=[('queued', 'En file'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='queued', max_length=20, verbose_name='Statut')),
                ('celery_task_id', models.CharField(blank=True, max_length=36, verbose_name='ID tâche Celery')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document', verbose_name='Document')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
            ],
            options={
                'verbose_name': 'File OCR',
                'verbose_name_plural': 'Files OCR',
                'ordering': ['-priority', 'created'],
                'indexes': [models.Index(fields=['status', 'priority', 'created'], name='paperless_o_status_b9a9e5_idx'), models.Index(fields=['celery_task_id'], name='paperless_o_celery__45c244_idx')],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('tesseract', 'Tesseract'), ('doctr', 'Doctr'), ('hybrid', 'Hybrid Fusion')], max_length=20, verbose_name='Moteur OCR')),
                ('text', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('confidence', models.FloatField(blank=True, help_text='Score de confiance moyen (0.0 à 1.0)', null=True, verbose_name='Score de confiance')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Temps de traitement (s)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('page_results', models.JSONField(blank=True, default=list, verbose_name='Résultats par page')),
                ('bounding_boxes', models.JSONField(blank=True, default=list, verbose_name='Boîtes englobantes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paperless_ocr.ocrconfiguration', verbose_name='Configuration utilisée')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Résultat OCR',
                'verbose_name_plural': 'Résultats OCR',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['document'], name='paperless_o_documen_da9ecc_idx'), models.Index(fields=['engine'], name='paperless_o_engine_dc291e_idx'), models.Index(fields=['created'], name='paperless_o_created_c0235e_idx'), models.Index(fields=['status'], name='paperless_o_status_99e07c_idx'), models.Index(condition=models.Q(('confidence__isnull', False)), fields=['confidence'], name='ocr_result_confidence_idx'), models.Index(condition=models.Q(('processing_time__isnull', False)), fields=['processing_time'], name='ocr_result_processing_time_idx')],
                'unique_together': {('document', 'engine')},
            },
        ),
    ]
