# Generated by Django 4.2.11 on 2024-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0005_alter_applicationconfiguration_ocr_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='ocr_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sets key for advanced version'),
        ),
    ]
