# Generated by Django 4.2.11 on 2024-08-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0006_alter_applicationconfiguration_ocr_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='ocr_key',
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='api_args',
            field=models.JSONField(null=True, verbose_name='Adds additional user arguments for OCRMyPDF'),
        ),
    ]
