# Generated by Django 4.2.11 on 2024-08-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0007_remove_applicationconfiguration_ocr_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='api_args',
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='password_ocr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='password_ocr_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='url_ocr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='url_ocr_field',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='username_ocr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='username_ocr_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
