# Generated by Django 4.2.11 on 2024-08-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0008_remove_applicationconfiguration_api_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='url_ocr',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='url_ocr_field',
            field=models.JSONField(null=True),
        ),
    ]
