# Generated by Django 4.2.11 on 2024-08-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0009_alter_applicationconfiguration_url_ocr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfiguration',
            old_name='url_ocr',
            new_name='api_ocr',
        ),
        migrations.RenameField(
            model_name='applicationconfiguration',
            old_name='url_ocr_field',
            new_name='api_ocr_field',
        ),
    ]
