# Generated by Django 4.2.11 on 2024-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0010_rename_url_ocr_applicationconfiguration_api_ocr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='enable_ocr',
            field=models.BooleanField(default=False, null=True, verbose_name='Enables ocr'),
        ),
    ]
