# Generated by Django 4.2.11 on 2024-08-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0011_applicationconfiguration_enable_ocr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='api_ocr',
        ),
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='api_ocr_field',
        ),
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='password_ocr',
        ),
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='password_ocr_field',
        ),
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='username_ocr',
        ),
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='username_ocr_field',
        ),
    ]
