# Generated by Django 4.2.11 on 2025-03-20 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0013_applicationconfiguration_password_ocr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='enable_compress',
            field=models.BooleanField(default=False, null=True, verbose_name='Enables compress'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='quality',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='sets quanlity compression'),
        ),
    ]
