# Generated by Django 4.2.11 on 2025-03-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edoc', '0014_applicationconfiguration_enable_compress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfiguration',
            old_name='quality',
            new_name='quality_compress',
        ),
    ]
