#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash

declare -r log_prefix="[init-checks]"

# Explicitly run the Django system checks
echo "${log_prefix} Running Django checks"

cd "${PAPERLESS_SRC_DIR}"

if [[ -n "${USER_IS_NON_ROOT}" ]]; then
	python3 manage.py check
else
	s6-setuidgid paperless python3 manage.py check
fi
